### ISSUE TITLE
Post an error message when typing in the wrong password

### ISSUE THREAD

**Issue by sJarl** [ravenclaw900/DietPi-Dashboard#103]
It would be wonderful if the password prompt would give you some indication that the wrong password was input.

Saves you from trying several times wondering why nothing works.

All the best

**Comment by ravenclaw900** [comment]
Good idea, lets you know if the app is frozen, the password is wrong, or something else has happened.

**Comment by ravenclaw900** [comment]
Added with https://github.com/ravenclaw900/DietPi-Dashboard/commit/02c540e43a443f9990c9913fec8f4cd5cd59e5ff.

**Comment by ravenclaw900** [comment]
Since this was included with v0.4.1, can the issue be closed?

**Comment by sJarl** [comment]
Yes. Many thanks!
