### ISSUE TITLE
RAM usage seems to be way off for processes

### ISSUE THREAD

**Issue by igorkulman** [ravenclaw900/DietPi-Dashboard#109]
RAM usage seems to be way off on my Rpi 2. 

For example the dashboard shows cloudflared with 795MiB and tailscaled with 788MiB. Both are more than the 720MiB the RPi can actually use.

<img width="1113" alt="Screen Shot 2022-01-07 at 15 57 55" src="https://user-images.githubusercontent.com/4746070/148562216-37f63496-2b26-4ab9-a9ef-c6c177c37c0d.png">

compared to htop showing cloudflared with 21MB and tailscaled with 18MB.

<img width="896" alt="Screen Shot 2022-01-07 at 15 58 09" src="https://user-images.githubusercontent.com/4746070/148562263-1d8313c0-2fc5-4c02-abbe-e6570fa3fb4d.png">

**Comment by ravenclaw900** [comment]
Hi,
The dashboard uses the virtual memory of a process, which is, according to the docs of the system information library that I use, "the total amount of memory used by the process". `htop` by default uses resident set size, which is, also according to the docs, "the amount of non-swapped physical memory used by the process". If, in `htop`, you enable the `M_VIRT` column under `Setup`, you should get the same value as the dashboard.

**Comment by igorkulman** [comment]
Would it be possible maybe to add a switch to toggle between those 2 values?

**Comment by MichaIng** [comment]
My two cents:
- The virtual memory is indeed no practical indicator for actual memory consumption of processes. Depending on the process, e.g. when heavily threaded like a webserver or database which *can* but not *does* currently handle a lot of concurrent connections, the virtual memory may be magnitudes of orders higher than what the process actually takes. It is more like an upper bounding of what it *may* use. And it includes shared memory, like loaded shared libraries which are in fact used by multiple different processes concurrently. In case of multiple websever of PHP handler child processes, e.g. the virtual memory of each child process includes the shared features, like PHP OPcache, which is indeed shared across all PHP handler child processes and often makes the major parts of the whole PHP process memory consumption (virtual and physical).
- The resident memory consumption is *much* closer to what a single process really currently uses in memory. Adding up all resident memory values of the whole process list does not 100% precisely but close enough tell you how much memory is used and how much memory is hence available, before the OOM killer kicks in. Doing so with the virtual memory gives you quickly values much (sometimes magnitudes of orders) higher than the actual total system memory, and hence does not help at all to evaluate whether you need to tweak your serves or upgrade your RAM modules (on non-SBCs 😉) or not. And that practical aspect, to know from the memory consumption whether action is advised or not, is what IMHO is most important when showing these stats at all.

**Comment by ravenclaw900** [comment]
Alright, that makes sense, and it will match up completely with `htop` now. I'll switch it over to the resident memory.

**Comment by ravenclaw900** [comment]
Done with https://github.com/ravenclaw900/DietPi-Dashboard/commit/9d96c9087a5b4ef8653b7c04a81053bd78732ae8.

**Comment by igorkulman** [comment]
Thanks
