### ISSUE TITLE
[bug] rename a blank file, delete it

### ISSUE THREAD

**Issue by IIMustangII1151** [ravenclaw900/DietPi-Dashboard#117]
#### Required Information
- DietPi version | 
G_DIETPI_VERSION_CORE=8
G_DIETPI_VERSION_SUB=0
G_DIETPI_VERSION_RC=2
G_GITBRANCH='master'
G_GITOWNER='MichaIng'

- Distro version | 
 bullseye

- Kernel version | 
`5.10.0-10-amd64 #1 SMP Debian 5.10.84-1`

- SBC model | 
Native PC (x86_64)

- Power supply used |
battery laptop
- SDcard used | 
HDD 160gb

#### Additional Information (if applicable)
- Software title | dietpi-dashboard
- Was the software title installed freshly or updated/migrated?
installed freshly
- Can this issue be replicated on a fresh installation of DietPi?
yes
535e7b02-4f83-4c3e-a095-1a76da643fa2

#### Steps to reproduce

1. renaming a file, leaving the name blank, in dietpi-dashboard using file browser deletes the file from the system, even canceling the rename window

#### Expected behaviour

-renaming a file

#### Actual behaviour

- deletes the file from the system

#### Extra details

- ...

**Comment by ravenclaw900** [comment]
Hi,
For me, renaming a file to nothing crashes the dashboard (the file browser definitely needs more error handling), and canceling the window renames it to `null` (that needs to be fixed as well). Your problem is that when a file is renamed to nothing, it is deleted? What version of the dashboard are you using?

**Comment by IIMustangII1151** [comment]
the version I use is v0.4.1

I was exploring the options when I opened the box to rename the file, when I canceled the file just disappeared.
I did the process a few more times losing many files.
I ran to report something serious. and as I had backup I restored

**Comment by ravenclaw900** [comment]
Ah, I think I see what's happening. The first time you cancel a file, it renames it to `null`, every time after that it overwrites the old `null` file with a new `null` file. First of all, the dashboard needs to not rename files `null` on cancel, and second of all it should check for an already existing file with the same name before renaming it.

**Comment by ravenclaw900** [comment]
Your issue should be fixed with [`434a03a` (#123)](https://github.com/ravenclaw900/DietPi-Dashboard/pull/123/commits/434a03ab706c3bb06bd11922fec9da491464f48b), and I'll make a release with those fixes after I do everything else on the checklist.
