### ISSUE TITLE
[Suggestion] Store binaries with $(uname -m) suffix

### ISSUE THREAD

**Issue by MichaIng** [ravenclaw900/DietPi-Dashboard#12]
Currently there is a translation from the `uname -m` output, respectively architecture ID required to script/find the correct download. Using the `uname -m` output directly allows to skip this, and within DietPi scripts it is available as `$G_HW_ARCH_NAME` variable OOTB.
- `dietpi-dashboard-amd64` => `dietpi-dashboard-x86_64`
- `dietpi-dashboard-armv6` => `dietpi-dashboard-armv6l`
- `dietpi-dashboard-armv7` => `dietpi-dashboard-armv7l`
- `dietpi-dashboard-armv8` => `dietpi-dashboard-aarch64`

**Comment by MichaIng** [comment]
I'll update the `dietpi-software` code accordingly 👍. Also the README here needs update.

**Comment by ravenclaw900** [comment]
I'll also rename the release binaries.
