### ISSUE TITLE
Dashboard gets killed every so often

### ISSUE THREAD

**Issue by Bwangster12** [ravenclaw900/DietPi-Dashboard#128]
I'm noticing that every few days, the DietPi Dashboard gets killed for an unknown reason.  I'm able to use everything else, SMB shares, Plex, etc... just can't access the Dashboard til I do a systemctl restart dietpi-dashboard.

Here is what I see in the logs for the last few days....

```
Jan 20 20:04:21 DietPi dietpi-dashboard[2456]: 2022-01-21 01:04:21,130 INFO  [dietpi_dashboard] Request to /assets/dietpi.4cc58251.png
Jan 20 20:04:21 DietPi dietpi-dashboard[2456]: 2022-01-21 01:04:21,132 INFO  [dietpi_dashboard] Request to /ws
Jan 20 20:04:21 DietPi dietpi-dashboard[2456]: 2022-01-21 01:04:21,214 INFO  [dietpi_dashboard] Request to /favicon.png
Jan 20 20:05:15 DietPi systemd[1]: dietpi-dashboard.service: A process of this unit has been killed by the OOM killer.
Jan 20 20:05:16 DietPi systemd[1]: dietpi-dashboard.service: Main process exited, code=killed, status=9/KILL
Jan 20 20:05:16 DietPi systemd[1]: dietpi-dashboard.service: Failed with result 'oom-kill'.
Jan 20 20:05:16 DietPi systemd[1]: dietpi-dashboard.service: Consumed 16.859s CPU time.
Jan 21 16:13:23 DietPi systemd[1]: Started Web Dashboard (DietPi).
Jan 21 16:13:23 DietPi dietpi-dashboard[404428]: 2022-01-21 21:13:23,438 INFO  [warp::server] Server::run; addr=0.0.0.0:5252
Jan 21 16:13:23 DietPi dietpi-dashboard[404428]: 2022-01-21 21:13:23,438 INFO  [warp::server] listening on http://0.0.0.0:5252
Jan 21 16:13:25 DietPi dietpi-dashboard[404428]: 2022-01-21 21:13:25,267 INFO  [dietpi_dashboard] Request to /
Jan 21 16:13:25 DietPi dietpi-dashboard[404428]: 2022-01-21 21:13:25,321 INFO  [dietpi_dashboard] Request to /assets/index.78a32cef.js
Jan 21 16:13:25 DietPi dietpi-dashboard[404428]: 2022-01-21 21:13:25,322 INFO  [dietpi_dashboard] Request to /assets/index.69f8c40f.css
Jan 21 16:13:25 DietPi dietpi-dashboard[404428]: 2022-01-21 21:13:25,324 INFO  [dietpi_dashboard] Request to /assets/xterm.6fe708e6.js
Jan 21 16:13:25 DietPi dietpi-dashboard[404428]: 2022-01-21 21:13:25,427 INFO  [dietpi_dashboard] Request to /ws
Jan 21 16:13:25 DietPi dietpi-dashboard[404428]: 2022-01-21 21:13:25,432 INFO  [dietpi_dashboard] Request to /assets/dietpi.4cc58251.png
Jan 21 16:13:25 DietPi dietpi-dashboard[404428]: 2022-01-21 21:13:25,634 INFO  [dietpi_dashboard] Request to /favicon.png
Jan 21 16:13:27 DietPi dietpi-dashboard[404428]: 2022-01-21 21:13:27,701 INFO  [dietpi_dashboard] Request to /login/
Jan 21 16:13:37 DietPi dietpi-dashboard[404428]: 2022-01-21 21:13:37,019 INFO  [dietpi_dashboard] Request to /ws/term
```

**Comment by Joulinar** [comment]
Your system is running out of memory (OOM) and processes getting killed.

```
killed by the OOM killer
```

have a look to `htop` for resource consumption and enlarge SWAP if needed.

**Comment by Bwangster12** [comment]
That's really weird to me.  I'm running a Beelink GK35 with n3350 and 4 gigs of ram.  I know not fastest thing in the world, but I only have Plex, Transmission, Samba, Adguard Home and Dietpi Dashboard on it.  Everytime I've looked at my stats, I see 0.51/3.6 GiB of RAM used.  Right now in htop, it shows 267M of 3.69G used.  Would something be spiking RAM usage causing this to happen?

**Comment by ravenclaw900** [comment]
The strange thing is, the OOM kill happened only a minute after you accessed the dashboard. Could you post a full log:
```
journalctl -u dietpi-dashboard
```

**Comment by Bwangster12** [comment]
-- Journal begins at Tue 2022-01-18 15:01:52 EST, ends at Sat 2022-01-22 08:47:43 EST. --
Jan 18 15:01:59 DietPi systemd[1]: Started Web Dashboard (DietPi).
Jan 18 15:01:59 DietPi dietpi-dashboard[530]: 2022-01-18 20:01:59,816 INFO  [warp::server] Server::run; addr=0.0.0.0:5252
Jan 18 15:01:59 DietPi dietpi-dashboard[530]: 2022-01-18 20:01:59,817 INFO  [warp::server] listening on http://0.0.0.0:5252
Jan 18 15:08:19 DietPi dietpi-dashboard[530]: 2022-01-18 20:08:19,482 INFO  [dietpi_dashboard] Request to /
Jan 18 15:08:19 DietPi dietpi-dashboard[530]: 2022-01-18 20:08:19,524 INFO  [dietpi_dashboard] Request to /assets/index.78a32cef.js
Jan 18 15:08:19 DietPi dietpi-dashboard[530]: 2022-01-18 20:08:19,525 INFO  [dietpi_dashboard] Request to /assets/index.69f8c40f.css
Jan 18 15:08:19 DietPi dietpi-dashboard[530]: 2022-01-18 20:08:19,528 INFO  [dietpi_dashboard] Request to /assets/xterm.6fe708e6.js
Jan 18 15:08:19 DietPi dietpi-dashboard[530]: 2022-01-18 20:08:19,625 INFO  [dietpi_dashboard] Request to /ws
Jan 18 15:08:19 DietPi dietpi-dashboard[530]: 2022-01-18 20:08:19,630 INFO  [dietpi_dashboard] Request to /assets/dietpi.4cc58251.png
Jan 18 15:12:33 DietPi dietpi-dashboard[530]: 2022-01-18 20:12:33,038 INFO  [dietpi_dashboard] Request to /
Jan 18 15:12:33 DietPi dietpi-dashboard[530]: 2022-01-18 20:12:33,080 INFO  [dietpi_dashboard] Request to /assets/index.69f8c40f.css
Jan 18 15:12:33 DietPi dietpi-dashboard[530]: 2022-01-18 20:12:33,080 INFO  [dietpi_dashboard] Request to /assets/index.78a32cef.js
Jan 18 15:12:33 DietPi dietpi-dashboard[530]: 2022-01-18 20:12:33,081 INFO  [dietpi_dashboard] Request to /assets/xterm.6fe708e6.js
Jan 18 15:12:33 DietPi dietpi-dashboard[530]: 2022-01-18 20:12:33,155 INFO  [dietpi_dashboard] Request to /ws
Jan 18 15:12:33 DietPi dietpi-dashboard[530]: 2022-01-18 20:12:33,160 INFO  [dietpi_dashboard] Request to /assets/dietpi.4cc58251.png
Jan 18 15:12:35 DietPi dietpi-dashboard[530]: 2022-01-18 20:12:35,431 INFO  [dietpi_dashboard] Request to /login/
Jan 18 15:18:23 DietPi systemd[1]: dietpi-dashboard.service: A process of this unit has been killed by the OOM killer.
Jan 18 15:18:25 DietPi systemd[1]: dietpi-dashboard.service: Main process exited, code=killed, status=9/KILL
Jan 18 15:18:25 DietPi systemd[1]: dietpi-dashboard.service: Failed with result 'oom-kill'.
Jan 18 15:18:25 DietPi systemd[1]: dietpi-dashboard.service: Consumed 23.727s CPU time.
Jan 18 16:18:36 DietPi systemd[1]: Started Web Dashboard (DietPi).
Jan 18 16:18:36 DietPi dietpi-dashboard[2456]: 2022-01-18 21:18:36,507 INFO  [warp::server] Server::run; addr=0.0.0.0:5252
Jan 18 16:18:36 DietPi dietpi-dashboard[2456]: 2022-01-18 21:18:36,507 INFO  [warp::server] listening on http://0.0.0.0:5252
Jan 18 16:18:38 DietPi dietpi-dashboard[2456]: 2022-01-18 21:18:38,293 INFO  [dietpi_dashboard] Request to /
Jan 18 16:18:38 DietPi dietpi-dashboard[2456]: 2022-01-18 21:18:38,332 INFO  [dietpi_dashboard] Request to /assets/index.78a32cef.js
Jan 18 16:18:38 DietPi dietpi-dashboard[2456]: 2022-01-18 21:18:38,333 INFO  [dietpi_dashboard] Request to /assets/index.69f8c40f.css
Jan 18 16:18:38 DietPi dietpi-dashboard[2456]: 2022-01-18 21:18:38,334 INFO  [dietpi_dashboard] Request to /assets/xterm.6fe708e6.js
Jan 18 16:18:38 DietPi dietpi-dashboard[2456]: 2022-01-18 21:18:38,411 INFO  [dietpi_dashboard] Request to /ws
Jan 18 16:18:38 DietPi dietpi-dashboard[2456]: 2022-01-18 21:18:38,415 INFO  [dietpi_dashboard] Request to /assets/dietpi.4cc58251.png
Jan 18 16:18:38 DietPi dietpi-dashboard[2456]: 2022-01-18 21:18:38,604 INFO  [dietpi_dashboard] Request to /favicon.png
Jan 18 16:18:40 DietPi dietpi-dashboard[2456]: 2022-01-18 21:18:40,470 INFO  [dietpi_dashboard] Request to /login/
Jan 18 20:14:35 DietPi dietpi-dashboard[2456]: 2022-01-19 01:14:35,408 INFO  [dietpi_dashboard] Request to /
Jan 18 20:14:35 DietPi dietpi-dashboard[2456]: 2022-01-19 01:14:35,436 INFO  [dietpi_dashboard] Request to /assets/xterm.6fe708e6.js
Jan 18 20:14:35 DietPi dietpi-dashboard[2456]: 2022-01-19 01:14:35,436 INFO  [dietpi_dashboard] Request to /assets/index.78a32cef.js
Jan 18 20:14:35 DietPi dietpi-dashboard[2456]: 2022-01-19 01:14:35,481 INFO  [dietpi_dashboard] Request to /assets/index.69f8c40f.css
Jan 18 20:14:35 DietPi dietpi-dashboard[2456]: 2022-01-19 01:14:35,567 INFO  [dietpi_dashboard] Request to /assets/dietpi.4cc58251.png
Jan 18 20:14:35 DietPi dietpi-dashboard[2456]: 2022-01-19 01:14:35,567 INFO  [dietpi_dashboard] Request to /ws
Jan 18 20:14:35 DietPi dietpi-dashboard[2456]: 2022-01-19 01:14:35,673 INFO  [dietpi_dashboard] Request to /favicon.png
Jan 18 20:14:40 DietPi dietpi-dashboard[2456]: 2022-01-19 01:14:40,451 INFO  [dietpi_dashboard] Request to /login/
Jan 19 07:31:05 DietPi dietpi-dashboard[2456]: 2022-01-19 12:31:05,022 INFO  [dietpi_dashboard] Request to /
Jan 19 07:31:05 DietPi dietpi-dashboard[2456]: 2022-01-19 12:31:05,059 INFO  [dietpi_dashboard] Request to /assets/index.78a32cef.js
Jan 19 07:31:05 DietPi dietpi-dashboard[2456]: 2022-01-19 12:31:05,060 INFO  [dietpi_dashboard] Request to /assets/xterm.6fe708e6.js
Jan 19 07:31:05 DietPi dietpi-dashboard[2456]: 2022-01-19 12:31:05,125 INFO  [dietpi_dashboard] Request to /assets/index.69f8c40f.css
Jan 19 07:31:05 DietPi dietpi-dashboard[2456]: 2022-01-19 12:31:05,231 INFO  [dietpi_dashboard] Request to /assets/dietpi.4cc58251.png
Jan 19 07:31:05 DietPi dietpi-dashboard[2456]: 2022-01-19 12:31:05,231 INFO  [dietpi_dashboard] Request to /ws
Jan 19 07:31:08 DietPi dietpi-dashboard[2456]: 2022-01-19 12:31:08,828 INFO  [dietpi_dashboard] Request to /login/
Jan 19 07:31:33 DietPi dietpi-dashboard[2456]: 2022-01-19 12:31:33,790 INFO  [dietpi_dashboard] Request to /ws/term
Jan 19 07:32:12 DietPi dietpi-dashboard[2456]: 2022-01-19 12:32:12,721 INFO  [dietpi_dashboard::terminal] Closed terminal
Jan 19 20:42:59 DietPi dietpi-dashboard[2456]: 2022-01-20 01:42:59,758 INFO  [dietpi_dashboard] Request to /
Jan 19 20:42:59 DietPi dietpi-dashboard[2456]: 2022-01-20 01:42:59,919 INFO  [dietpi_dashboard] Request to /assets/index.78a32cef.js
Jan 19 20:42:59 DietPi dietpi-dashboard[2456]: 2022-01-20 01:42:59,920 INFO  [dietpi_dashboard] Request to /assets/xterm.6fe708e6.js
Jan 19 20:42:59 DietPi dietpi-dashboard[2456]: 2022-01-20 01:42:59,969 INFO  [dietpi_dashboard] Request to /assets/index.69f8c40f.css
Jan 19 20:43:00 DietPi dietpi-dashboard[2456]: 2022-01-20 01:43:00,058 INFO  [dietpi_dashboard] Request to /ws
Jan 19 20:43:00 DietPi dietpi-dashboard[2456]: 2022-01-20 01:43:00,070 INFO  [dietpi_dashboard] Request to /assets/dietpi.4cc58251.png
Jan 19 20:43:05 DietPi dietpi-dashboard[2456]: 2022-01-20 01:43:05,498 INFO  [dietpi_dashboard] Request to /login/
Jan 20 12:44:28 DietPi dietpi-dashboard[2456]: 2022-01-20 17:44:28,650 INFO  [dietpi_dashboard] Request to /
Jan 20 12:44:28 DietPi dietpi-dashboard[2456]: 2022-01-20 17:44:28,700 INFO  [dietpi_dashboard] Request to /assets/index.78a32cef.js
Jan 20 12:44:28 DietPi dietpi-dashboard[2456]: 2022-01-20 17:44:28,700 INFO  [dietpi_dashboard] Request to /assets/index.69f8c40f.css
Jan 20 12:44:28 DietPi dietpi-dashboard[2456]: 2022-01-20 17:44:28,702 INFO  [dietpi_dashboard] Request to /assets/xterm.6fe708e6.js
Jan 20 12:44:28 DietPi dietpi-dashboard[2456]: 2022-01-20 17:44:28,776 INFO  [dietpi_dashboard] Request to /ws
Jan 20 12:44:28 DietPi dietpi-dashboard[2456]: 2022-01-20 17:44:28,780 INFO  [dietpi_dashboard] Request to /assets/dietpi.4cc58251.png
Jan 20 12:44:30 DietPi dietpi-dashboard[2456]: 2022-01-20 17:44:30,787 INFO  [dietpi_dashboard] Request to /login/
Jan 20 20:03:32 DietPi dietpi-dashboard[2456]: 2022-01-21 01:03:32,762 INFO  [dietpi_dashboard] Request to /
Jan 20 20:03:32 DietPi dietpi-dashboard[2456]: 2022-01-21 01:03:32,915 INFO  [dietpi_dashboard] Request to /assets/xterm.6fe708e6.js
Jan 20 20:03:32 DietPi dietpi-dashboard[2456]: 2022-01-21 01:03:32,915 INFO  [dietpi_dashboard] Request to /assets/index.78a32cef.js
Jan 20 20:03:32 DietPi dietpi-dashboard[2456]: 2022-01-21 01:03:32,980 INFO  [dietpi_dashboard] Request to /assets/index.69f8c40f.css
Jan 20 20:03:33 DietPi dietpi-dashboard[2456]: 2022-01-21 01:03:33,121 INFO  [dietpi_dashboard] Request to /assets/dietpi.4cc58251.png
Jan 20 20:03:33 DietPi dietpi-dashboard[2456]: 2022-01-21 01:03:33,121 INFO  [dietpi_dashboard] Request to /ws
Jan 20 20:03:36 DietPi dietpi-dashboard[2456]: 2022-01-21 01:03:36,962 INFO  [dietpi_dashboard] Request to /login/
Jan 20 20:04:05 DietPi dietpi-dashboard[2456]: 2022-01-21 01:04:05,930 INFO  [dietpi_dashboard] Request to /browser
Jan 20 20:04:05 DietPi dietpi-dashboard[2456]: 2022-01-21 01:04:05,990 INFO  [dietpi_dashboard] Request to /assets/index.78a32cef.js
Jan 20 20:04:06 DietPi dietpi-dashboard[2456]: 2022-01-21 01:04:06,057 INFO  [dietpi_dashboard] Request to /assets/index.69f8c40f.css
Jan 20 20:04:06 DietPi dietpi-dashboard[2456]: 2022-01-21 01:04:06,059 INFO  [dietpi_dashboard] Request to /assets/xterm.6fe708e6.js
Jan 20 20:04:06 DietPi dietpi-dashboard[2456]: 2022-01-21 01:04:06,189 INFO  [dietpi_dashboard] Request to /assets/dietpi.4cc58251.png
Jan 20 20:04:06 DietPi dietpi-dashboard[2456]: 2022-01-21 01:04:06,190 INFO  [dietpi_dashboard] Request to /ws
Jan 20 20:04:06 DietPi dietpi-dashboard[2456]: 2022-01-21 01:04:06,256 INFO  [dietpi_dashboard] Request to /favicon.png
Jan 20 20:04:20 DietPi dietpi-dashboard[2456]: 2022-01-21 01:04:20,855 INFO  [dietpi_dashboard] Request to /
Jan 20 20:04:20 DietPi dietpi-dashboard[2456]: 2022-01-21 01:04:20,898 INFO  [dietpi_dashboard] Request to /assets/index.78a32cef.js
Jan 20 20:04:20 DietPi dietpi-dashboard[2456]: 2022-01-21 01:04:20,946 INFO  [dietpi_dashboard] Request to /assets/index.69f8c40f.css
Jan 20 20:04:20 DietPi dietpi-dashboard[2456]: 2022-01-21 01:04:20,947 INFO  [dietpi_dashboard] Request to /assets/xterm.6fe708e6.js
Jan 20 20:04:21 DietPi dietpi-dashboard[2456]: 2022-01-21 01:04:21,130 INFO  [dietpi_dashboard] Request to /assets/dietpi.4cc58251.png
Jan 20 20:04:21 DietPi dietpi-dashboard[2456]: 2022-01-21 01:04:21,132 INFO  [dietpi_dashboard] Request to /ws
Jan 20 20:04:21 DietPi dietpi-dashboard[2456]: 2022-01-21 01:04:21,214 INFO  [dietpi_dashboard] Request to /favicon.png
Jan 20 20:05:15 DietPi systemd[1]: dietpi-dashboard.service: A process of this unit has been killed by the OOM killer.
Jan 20 20:05:16 DietPi systemd[1]: dietpi-dashboard.service: Main process exited, code=killed, status=9/KILL
Jan 20 20:05:16 DietPi systemd[1]: dietpi-dashboard.service: Failed with result 'oom-kill'.
Jan 20 20:05:16 DietPi systemd[1]: dietpi-dashboard.service: Consumed 16.859s CPU time.
Jan 21 16:13:23 DietPi systemd[1]: Started Web Dashboard (DietPi).
Jan 21 16:13:23 DietPi dietpi-dashboard[404428]: 2022-01-21 21:13:23,438 INFO  [warp::server] Server::run; addr=0.0.0.0:5252
Jan 21 16:13:23 DietPi dietpi-dashboard[404428]: 2022-01-21 21:13:23,438 INFO  [warp::server] listening on http://0.0.0.0:5252
Jan 21 16:13:25 DietPi dietpi-dashboard[404428]: 2022-01-21 21:13:25,267 INFO  [dietpi_dashboard] Request to /
Jan 21 16:13:25 DietPi dietpi-dashboard[404428]: 2022-01-21 21:13:25,321 INFO  [dietpi_dashboard] Request to /assets/index.78a32cef.js
Jan 21 16:13:25 DietPi dietpi-dashboard[404428]: 2022-01-21 21:13:25,322 INFO  [dietpi_dashboard] Request to /assets/index.69f8c40f.css
Jan 21 16:13:25 DietPi dietpi-dashboard[404428]: 2022-01-21 21:13:25,324 INFO  [dietpi_dashboard] Request to /assets/xterm.6fe708e6.js
Jan 21 16:13:25 DietPi dietpi-dashboard[404428]: 2022-01-21 21:13:25,427 INFO  [dietpi_dashboard] Request to /ws
Jan 21 16:13:25 DietPi dietpi-dashboard[404428]: 2022-01-21 21:13:25,432 INFO  [dietpi_dashboard] Request to /assets/dietpi.4cc58251.png
Jan 21 16:13:25 DietPi dietpi-dashboard[404428]: 2022-01-21 21:13:25,634 INFO  [dietpi_dashboard] Request to /favicon.png
Jan 21 16:13:27 DietPi dietpi-dashboard[404428]: 2022-01-21 21:13:27,701 INFO  [dietpi_dashboard] Request to /login/
Jan 21 16:13:37 DietPi dietpi-dashboard[404428]: 2022-01-21 21:13:37,019 INFO  [dietpi_dashboard] Request to /ws/term
Jan 21 16:14:56 DietPi dietpi-dashboard[404428]: 2022-01-21 21:14:56,881 INFO  [dietpi_dashboard::terminal] Closed terminal
Jan 21 17:29:02 DietPi dietpi-dashboard[404428]: 2022-01-21 22:29:02,261 INFO  [dietpi_dashboard] Request to /
Jan 21 17:29:02 DietPi dietpi-dashboard[404428]: 2022-01-21 22:29:02,306 INFO  [dietpi_dashboard] Request to /assets/index.78a32cef.js
Jan 21 17:29:02 DietPi dietpi-dashboard[404428]: 2022-01-21 22:29:02,307 INFO  [dietpi_dashboard] Request to /assets/xterm.6fe708e6.js
Jan 21 17:29:02 DietPi dietpi-dashboard[404428]: 2022-01-21 22:29:02,362 INFO  [dietpi_dashboard] Request to /assets/index.69f8c40f.css
Jan 21 17:29:02 DietPi dietpi-dashboard[404428]: 2022-01-21 22:29:02,487 INFO  [dietpi_dashboard] Request to /ws
Jan 21 17:29:02 DietPi dietpi-dashboard[404428]: 2022-01-21 22:29:02,492 INFO  [dietpi_dashboard] Request to /assets/dietpi.4cc58251.png
Jan 21 17:29:08 DietPi dietpi-dashboard[404428]: 2022-01-21 22:29:08,414 INFO  [dietpi_dashboard] Request to /login/
Jan 21 17:30:00 DietPi dietpi-dashboard[404428]: 2022-01-21 22:30:00,500 INFO  [dietpi_dashboard::sockets] uninstalling software with ID(s) ["162", "185"]
Jan 21 17:30:38 DietPi dietpi-dashboard[404428]: 2022-01-21 22:30:38,738 INFO  [dietpi_dashboard] Request to /software
Jan 21 17:30:38 DietPi dietpi-dashboard[404428]: 2022-01-21 22:30:38,801 INFO  [dietpi_dashboard] Request to /assets/index.78a32cef.js
Jan 21 17:30:38 DietPi dietpi-dashboard[404428]: 2022-01-21 22:30:38,803 INFO  [dietpi_dashboard] Request to /assets/xterm.6fe708e6.js
Jan 21 17:30:38 DietPi dietpi-dashboard[404428]: 2022-01-21 22:30:38,867 INFO  [dietpi_dashboard] Request to /assets/index.69f8c40f.css
Jan 21 17:30:39 DietPi dietpi-dashboard[404428]: 2022-01-21 22:30:39,004 INFO  [dietpi_dashboard] Request to /assets/dietpi.4cc58251.png
Jan 21 17:30:39 DietPi dietpi-dashboard[404428]: 2022-01-21 22:30:39,007 INFO  [dietpi_dashboard] Request to /ws
Jan 21 17:30:39 DietPi dietpi-dashboard[404428]: 2022-01-21 22:30:39,041 INFO  [dietpi_dashboard] Request to /favicon.png
Jan 21 17:33:59 DietPi dietpi-dashboard[404428]: 2022-01-21 22:33:59,644 INFO  [dietpi_dashboard] Request to /
Jan 21 17:33:59 DietPi dietpi-dashboard[404428]: 2022-01-21 22:33:59,769 INFO  [dietpi_dashboard] Request to /assets/index.78a32cef.js
Jan 21 17:33:59 DietPi dietpi-dashboard[404428]: 2022-01-21 22:33:59,770 INFO  [dietpi_dashboard] Request to /assets/xterm.6fe708e6.js
Jan 21 17:33:59 DietPi dietpi-dashboard[404428]: 2022-01-21 22:33:59,834 INFO  [dietpi_dashboard] Request to /assets/index.69f8c40f.css
Jan 21 17:33:59 DietPi dietpi-dashboard[404428]: 2022-01-21 22:33:59,937 INFO  [dietpi_dashboard] Request to /ws
Jan 21 17:33:59 DietPi dietpi-dashboard[404428]: 2022-01-21 22:33:59,938 INFO  [dietpi_dashboard] Request to /assets/dietpi.4cc58251.png
Jan 21 21:41:38 DietPi dietpi-dashboard[404428]: 2022-01-22 02:41:38,773 INFO  [dietpi_dashboard] Request to /
Jan 21 21:41:38 DietPi dietpi-dashboard[404428]: 2022-01-22 02:41:38,982 INFO  [dietpi_dashboard] Request to /assets/index.78a32cef.js
Jan 21 21:41:38 DietPi dietpi-dashboard[404428]: 2022-01-22 02:41:38,983 INFO  [dietpi_dashboard] Request to /assets/xterm.6fe708e6.js
Jan 21 21:41:39 DietPi dietpi-dashboard[404428]: 2022-01-22 02:41:39,048 INFO  [dietpi_dashboard] Request to /assets/index.69f8c40f.css
Jan 21 21:41:39 DietPi dietpi-dashboard[404428]: 2022-01-22 02:41:39,134 INFO  [dietpi_dashboard] Request to /assets/dietpi.4cc58251.png
Jan 21 21:41:39 DietPi dietpi-dashboard[404428]: 2022-01-22 02:41:39,136 INFO  [dietpi_dashboard] Request to /ws
Jan 21 21:41:43 DietPi dietpi-dashboard[404428]: 2022-01-22 02:41:43,237 INFO  [dietpi_dashboard] Request to /login/
Jan 21 21:44:15 DietPi dietpi-dashboard[404428]: 2022-01-22 02:44:15,507 INFO  [dietpi_dashboard] Request to /
Jan 21 21:44:15 DietPi dietpi-dashboard[404428]: 2022-01-22 02:44:15,567 INFO  [dietpi_dashboard] Request to /assets/xterm.6fe708e6.js
Jan 21 21:44:15 DietPi dietpi-dashboard[404428]: 2022-01-22 02:44:15,567 INFO  [dietpi_dashboard] Request to /assets/index.78a32cef.js
Jan 21 21:44:15 DietPi dietpi-dashboard[404428]: 2022-01-22 02:44:15,632 INFO  [dietpi_dashboard] Request to /assets/index.69f8c40f.css
Jan 21 21:44:15 DietPi dietpi-dashboard[404428]: 2022-01-22 02:44:15,708 INFO  [dietpi_dashboard] Request to /assets/dietpi.4cc58251.png
Jan 21 21:44:15 DietPi dietpi-dashboard[404428]: 2022-01-22 02:44:15,712 INFO  [dietpi_dashboard] Request to /ws
Jan 21 21:44:15 DietPi dietpi-dashboard[404428]: 2022-01-22 02:44:15,763 INFO  [dietpi_dashboard] Request to /favicon.png
Jan 21 21:44:19 DietPi dietpi-dashboard[404428]: 2022-01-22 02:44:19,634 INFO  [dietpi_dashboard] Request to /ws/term
Jan 21 21:47:09 DietPi dietpi-dashboard[404428]: 2022-01-22 02:47:09,340 INFO  [dietpi_dashboard::terminal] Closed terminal
Jan 21 21:48:51 DietPi dietpi-dashboard[404428]: 2022-01-22 02:48:51,457 INFO  [dietpi_dashboard] Request to /terminal
Jan 21 21:48:51 DietPi dietpi-dashboard[404428]: 2022-01-22 02:48:51,504 INFO  [dietpi_dashboard] Request to /assets/index.78a32cef.js
Jan 21 21:48:51 DietPi dietpi-dashboard[404428]: 2022-01-22 02:48:51,505 INFO  [dietpi_dashboard] Request to /assets/xterm.6fe708e6.js
Jan 21 21:48:51 DietPi dietpi-dashboard[404428]: 2022-01-22 02:48:51,571 INFO  [dietpi_dashboard] Request to /assets/index.69f8c40f.css
Jan 21 21:48:51 DietPi dietpi-dashboard[404428]: 2022-01-22 02:48:51,701 INFO  [dietpi_dashboard] Request to /assets/dietpi.4cc58251.png
Jan 21 21:48:51 DietPi dietpi-dashboard[404428]: 2022-01-22 02:48:51,702 INFO  [dietpi_dashboard] Request to /ws
Jan 21 21:48:51 DietPi dietpi-dashboard[404428]: 2022-01-22 02:48:51,734 INFO  [dietpi_dashboard] Request to /ws/term
Jan 21 21:48:51 DietPi dietpi-dashboard[404428]: 2022-01-22 02:48:51,767 INFO  [dietpi_dashboard] Request to /favicon.png
Jan 22 07:20:56 DietPi dietpi-dashboard[404428]: 2022-01-22 12:20:56,521 INFO  [dietpi_dashboard] Request to /
Jan 22 07:20:56 DietPi dietpi-dashboard[404428]: 2022-01-22 12:20:56,565 INFO  [dietpi_dashboard] Request to /assets/index.78a32cef.js
Jan 22 07:20:56 DietPi dietpi-dashboard[404428]: 2022-01-22 12:20:56,633 INFO  [dietpi_dashboard] Request to /assets/index.69f8c40f.css
Jan 22 07:20:56 DietPi dietpi-dashboard[404428]: 2022-01-22 12:20:56,634 INFO  [dietpi_dashboard] Request to /assets/xterm.6fe708e6.js
Jan 22 07:20:56 DietPi dietpi-dashboard[404428]: 2022-01-22 12:20:56,719 INFO  [dietpi_dashboard] Request to /ws
Jan 22 07:20:56 DietPi dietpi-dashboard[404428]: 2022-01-22 12:20:56,724 INFO  [dietpi_dashboard] Request to /assets/dietpi.4cc58251.png
Jan 22 07:21:07 DietPi dietpi-dashboard[404428]: 2022-01-22 12:21:07,497 INFO  [dietpi_dashboard] Request to /login/

**Comment by ravenclaw900** [comment]
@MichaIng, any ideas? It seems to be related to the dashboard, because it always seems to happen within 10 minutes of a dashboard page loading, but I can't find any memory leaks.

**Comment by MichaIng** [comment]
I just installed it on my server (nightly) and keep watching it now. @Bwangster12 did you install the stable or nightly version and do you have other backend nodes added, just so that we can try to replicate with a setup as close to yours as possible. I sadly have no `x86_64` system persistently running for doing a long-term test.

Probably you can run something like that to monitor and log high overall and dashboard memory usage to a file:
```sh
cat << '_EOF_' > memory_dashboard.sh
#!/bin/bash
pid=$(pidof dietpi-dashboard)
while sleep 2
do
mem_avail=$(mawk '/^MemAvailable:/{print $2}' /proc/meminfo)
(( $mem_avail < 524288 )) || continue
mem_dashboard=$(ps --no-headers -p 10356 -o rss)
date -u
echo -e "Available memory: $mem_avail KiB\nDashboard usage: $mem_dashboard KiB\n"
done
_EOF_
chmod +x memory_dashboard.sh
./memory_dashboard.sh > memory_dashboard.log &
```
You can kill it with:
```sh
killall -w memory_dashboard.sh
```
It should then log, whenever available memory is below 512 MiB, something like that (I needed to adjust the value to have something logged 😉):
```
Sat Jan 22 20:22:03 UTC 2022
Available memory: 718248 KiB
Dashboard usage:  1904 KiB

Sat Jan 22 20:22:05 UTC 2022
Available memory: 718072 KiB
Dashboard usage:  1904 KiB

Sat Jan 22 20:22:07 UTC 2022
Available memory: 718016 KiB
Dashboard usage:  1904 KiB

Sat Jan 22 20:22:09 UTC 2022
Available memory: 718776 KiB
Dashboard usage:  1904 KiB

Sat Jan 22 20:22:11 UTC 2022
Available memory: 719056 KiB
Dashboard usage:  1904 KiB

...
```
So once memory usage goes into (relative to overall memory) critical range, you are able to review its development as well as how much the dashboard consumed.

**Comment by Bwangster12** [comment]
I installed the Stable version...  I'm a bit of a newb, but don't think I have other backend nodes.  If by that you mean "software," I have Plex, Transmission, Samba Server, Dietpi-RAMlog, Dropbear, Adguard Home and DietPi Dashboard.  The only other thing I did is followed this (https://dietpi.com/phpbb/viewtopic.php?t=7619) and am using my RAM for transcoding Plex videos, but I don't really have to transcode much.

**Comment by MichaIng** [comment]
> I'm a bit of a newb, but don't think I have other backend nodes.

Then you don't, it's the new feature that you can install DietPi-Dashboard as backend only on other DietPi systems and then add and manage them from a single dashboard interface. But this needs to be done manually.

Transmission and Plex while transcoding can consume quite a lot of memory, but we can only guess without monitoring their actual RAM usage. And indeed it looks like it is the dashboard itself. You can copy&paste the first command block above into your SSH console to start memory peak logging, lets see what the result is on next crash.

**Comment by ravenclaw900** [comment]
Any updates? Has the dashboard crashed again?

**Comment by ravenclaw900** [comment]
Closing, please reopen if it is still an issue.
