### ISSUE TITLE
TLS support for elliptic curve (ec-384) keys

### ISSUE THREAD

**Issue by MichaIng** [ravenclaw900/DietPi-Dashboard#129]
I just wanted to setup TLS on my server, which doesn't use an RSA key but EC, ec-384 to be precise, but the dashboard doesn't start up with it:
```
dietpi-dashboard[10205]: thread 'main' panicked at 'error binding to 0.0.0.0:5252: key contains no private key', /cargo/registry/src/github.com-1ecc6299db9ec823/warp-0.3.2/src/server.rs:534:27
```
=> https://github.com/seanmonstar/warp/blob/master/src/server.rs#L534

It looks like `1ecc6299db9ec823` contains "ecc" and "ec", but I'm sure this is a coincidence while it is a commit ID/hash. Not sure whether warp doesn't support EC keys or whether support can be enabled? The docs do not really give a hint: https://docs.rs/warp/latest/warp/struct.TlsServer.html

Checking the sources, it indeed seems that only plain RSA and PKCS8 format are supported: https://github.com/seanmonstar/warp/blob/master/src/tls.rs#L22

The EC keys look like this:
```
-----BEGIN EC PARAMETERS-----
XXXXXXX
-----END EC PARAMETERS-----
-----BEGIN EC PRIVATE KEY-----
XXXXXXX
-----END EC PRIVATE KEY-----
```
So indeed it looks like this would be a highly welcome upstream feature, since EC keys are widely supported nowadays and highly superior to RSA keys in terms of security/size factor.

**Comment by MichaIng** [comment]
Ah found it:
```sh
openssl pkcs8 -topk8 -nocrypt -in ecc.key -out ecc.pkcs8.pem
```
Converts the EC key into PKCS8 format, which makes it work with the dashboard 👍. Marking this as closed.

**Comment by ravenclaw900** [comment]
Just a note, warp uses the [rustls](https://docs.rs/rustls) for providing TLS support, and [rustls_pemfile](https://docs.rs/rustls_pemfile) for parsing keys. See the corresponding requests: https://github.com/rustls/pemfile/issues/4, https://github.com/rustls/rustls/issues/767, which suggest your solution.

**Comment by MichaIng** [comment]
Ah great. Would be smooth indeed to support EC keys directly, but converting to PKCS8 via deploy hook is not a big issue.
