### ISSUE TITLE
[Feature] [Processes] Allow to hide kernel and/or userland threads

### ISSUE THREAD

**Issue by MichaIng** [ravenclaw900/DietPi-Dashboard#13]
Kernel threads are often cryptic to users and userland process threads may add a long list of duplicates of a single process, which doesn't help much with getting some overview.

Similar to how it is set by default in `htop`, it would hence be nice to allow hiding kernel threads and userland threads for the process list, or really show only "processes" (instead of threads) by default, so that it is aligned with what users see in `htop`.

**Comment by ravenclaw900** [comment]
Currently it just skips them by default, if you want we could add a config file option for it.

**Comment by MichaIng** [comment]
Fixed with: https://github.com/ravenclaw900/DietPi-Dashboard/commit/4a0ab2d22af5bb3dfc59ef6769220e943ac03245

👍

I think it makes sense like this. Further options can be added in the future, when requested.
