### ISSUE TITLE
data isn't saved and no network activity

### ISSUE THREAD

**Issue by BeekeeperNL** [ravenclaw900/DietPi-Dashboard#153]
**Describe the bug**:
When i refresh the site the statistics graphs are always empty. data isn't logged.
Network activity is not visible at all there is a line through them.

**Version of DietPi-Dashboard**: 
DietPi-Dashboard [v0.5.0](https://github.com/ravenclaw900/DietPi-Dashboard/releases/tag/v0.5.0)

**Nightly or stable**: | Stable

**Version of DietPi**: 8.1.2

**Device architecture**: 
Its a HPt530 WBT with an AMD embedded 215JJ processor

**To Reproduce**

1. Go to '...'Dashboard
2. Click on '....'F5 - refresh
4. See error - All de data is gone from the staticics grph

**Error log**

root@DietPi:/# journalctl -u dietpi-dashboard
-- Journal begins at Thu 2022-02-10 12:16:56 CET, ends at Thu 2022-02-10 17:27:33 CET. --
Feb 10 16:50:02 DietPi dietpi-dashboard[597]: INFO  [dietpi_dashboard] Request to /
Feb 10 16:50:02 DietPi dietpi-dashboard[597]: INFO  [dietpi_dashboard] Request to /assets/index.592bbc0d.js
Feb 10 16:50:02 DietPi dietpi-dashboard[597]: INFO  [dietpi_dashboard] Request to /assets/index.eaf4e9a8.css
Feb 10 16:50:02 DietPi dietpi-dashboard[597]: INFO  [dietpi_dashboard] Request to /assets/xterm.7cca9343.js
Feb 10 16:50:03 DietPi dietpi-dashboard[597]: INFO  [dietpi_dashboard] Request to /ws
Feb 10 16:50:03 DietPi dietpi-dashboard[597]: INFO  [dietpi_dashboard] Request to /assets/dietpi.4cc58251.png
Feb 10 16:56:21 DietPi dietpi-dashboard[597]: INFO  [dietpi_dashboard] Request to /
Feb 10 16:56:21 DietPi dietpi-dashboard[597]: INFO  [dietpi_dashboard] Request to /assets/index.592bbc0d.js
Feb 10 16:56:21 DietPi dietpi-dashboard[597]: INFO  [dietpi_dashboard] Request to /assets/index.eaf4e9a8.css
Feb 10 16:56:21 DietPi dietpi-dashboard[597]: INFO  [dietpi_dashboard] Request to /assets/xterm.7cca9343.js
Feb 10 16:56:21 DietPi dietpi-dashboard[597]: INFO  [dietpi_dashboard] Request to /assets/dietpi.4cc58251.png
Feb 10 16:56:21 DietPi dietpi-dashboard[597]: INFO  [dietpi_dashboard] Request to /ws
Feb 10 16:56:22 DietPi dietpi-dashboard[597]: INFO  [dietpi_dashboard] Request to /favicon.png
Feb 10 16:59:05 DietPi dietpi-dashboard[597]: INFO  [dietpi_dashboard] Request to /login/
Feb 10 16:59:08 DietPi dietpi-dashboard[597]: INFO  [dietpi_dashboard] Request to /login/
Feb 10 16:59:15 DietPi dietpi-dashboard[597]: INFO  [dietpi_dashboard] Request to /login/
Feb 10 16:59:32 DietPi dietpi-dashboard[597]: INFO  [dietpi_dashboard] Request to /process
Feb 10 16:59:32 DietPi dietpi-dashboard[597]: INFO  [dietpi_dashboard] Request to /assets/index.592bbc0d.js
Feb 10 16:59:32 DietPi dietpi-dashboard[597]: INFO  [dietpi_dashboard] Request to /assets/index.eaf4e9a8.css
Feb 10 16:59:32 DietPi dietpi-dashboard[597]: INFO  [dietpi_dashboard] Request to /assets/xterm.7cca9343.js
Feb 10 16:59:32 DietPi dietpi-dashboard[597]: INFO  [dietpi_dashboard] Request to /ws
Feb 10 16:59:32 DietPi dietpi-dashboard[597]: INFO  [dietpi_dashboard] Request to /assets/dietpi.4cc58251.png
Feb 10 16:59:32 DietPi dietpi-dashboard[597]: INFO  [dietpi_dashboard] Request to /favicon.png
Feb 10 17:12:58 DietPi dietpi-dashboard[597]: INFO  [dietpi_dashboard] Request to /ws/term
Feb 10 17:24:21 DietPi dietpi-dashboard[597]: INFO  [dietpi_dashboard] Request to /ws/term

**Additional context**

**Comment by ravenclaw900** [comment]
Hello,
This is intended, all the data, once sent, is stored locally in your browser. It is not supposed to stay. The network should actually be there, however the amount of data sent every second is really low, so you might have to disable the other lines to get it to appear.

**Comment by MichaIng** [comment]
> it appears as designed then. in my opinion it should be stored at least until a reboot so that you can see how the system is performing. longer term statistical data would be much more interesting to see.

This data is not stored on the server but in your volatile browser storage currently. What you are requesting would be something like Netdata does, hence that the server/backend constantly obtains and stores data for e.g. a fixed time range and presents that full time range to clients. Not sure whether we want that, would be quite a different approach, probably as optional feature?

**Comment by ravenclaw900** [comment]
@BeekeeperNL, if you feel like testing the latest nightly, I've actually replaced the charting library (for different reasons), so see if it works better for you.

**Comment by ravenclaw900** [comment]
Closing, should be fixed with `v0.6.0`.

**Comment by surtarso** [comment]
Hi, sorry to necro this, but I ended up here thinking my network wasn't being monitored at all and searching for a solution.
So what I got is that it is measuring the data the same way that the ram/swap/disk combo is measured. So if you have a big disk, or a lot of ram, it is minuscule in comparison and you cant really monitor both at the same time meaningfully.

My 2 cents if I may, you could make in a way that the current session's high peak represents 100%, so it will always dynamically adjust itself to be visible on the graph. The values on the legend on the bottom could still be in MB's so we can keep track, but the lines of the graph could be based on latest high peak = 100% and the network idle "problem" should be fixed, no? idk, I liked it =)

<3 you dashboard, thx!
