### ISSUE TITLE
get rid of the login in window?

### ISSUE THREAD

**Issue by Uli007git** [ravenclaw900/DietPi-Dashboard#155]
**Describe the bug**:
Not really a bug, but can I get rid of the login window when I open the dashboard? It's a bit annoying 👎 

**Version of DietPi-Dashboard**: 0.5.0

**Nightly or stable**: Stable

Thanks

**Comment by MichaIng** [comment]
Check out `/opt/dietpi-dashboard/config.toml`:
```sh
G_CONFIG_INJECT 'pass[[:blank:]]' 'pass = false' /opt/dietpi-dashboard/config.toml
systemctl restart dietpi-dashboard
```

**Comment by MichaIng** [comment]
By times, another nice feature would be to bind to IPs and to restrict access to specific IPs. However, for now iptables or another firewall can be used to restrict access.

**Comment by MichaIng** [comment]
Great, I'll mark this as closed then.
