### ISSUE TITLE
[Bug] File Browser crashes service

### ISSUE THREAD

**Issue by MichaIng** [ravenclaw900/DietPi-Dashboard#18]
```
Nov 06 18:16:50 VM-Bullseye dietpi-dashboard[47807]: thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', src/sockets.rs:216:47
Nov 06 18:16:50 VM-Bullseye dietpi-dashboard[47807]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by MichaIng** [comment]
We shouldn't count on environment variables in general, here the `HOME` variable seems to not be set. We could either use `/root` as long as this is the fixed user or `~` if this is supported? Not hints in the docs about this: https://doc.rust-lang.org/std/fs/fn.read_dir.html

**Comment by ravenclaw900** [comment]
The browser will be running as root, but should we set the default path to `/home/dietpi`, since that's probably what most people would expect.

**Comment by MichaIng** [comment]
I hope no one expects `/home/dietpi` as it will be removed soon together with the `dietpi` user, in favour of a custom user creation option on first login. Let's do not mess with a different users home directory.

This is also in a personal interest since I have the `dietpi` user and it's home removed on all my production systems 😄.
