### ISSUE TITLE
Set a token expiry time doesn't work

### ISSUE THREAD

**Issue by JappeHallunken** [ravenclaw900/DietPi-Dashboard#185]
I set a token expire time in config.yml.
For testing I set it to really low values (0 and 1 and 10)
But I still can access the dashboard after closing the tab or even the whole browser, and waited for the set time.

It only worked correctly in Incognito / private mode (I tested Firefox and Chrome), but this makes sense, because the token gets immediatly deleted after closing the tab, no matter which time is configured inside the dashboard.

**Version of DietPi-Dashboard**: 0.5.1

**Nightly or stable**: both, but only stable worked correct, nightly didn't showed statistics, which is another problem not related to this ;)

**Version of DietPi**: 8.2.2

**Device architecture**: armv8

**To Reproduce**

1. Install dashboard
2. add `expiry = <some value>` in  `/opt/dietpi-dashboard/config.toml`
3. restart dashboard service
4. browse to dashboard in browser
5. insert password
6. close the tab/brwoser and reopen page for dashboard
7. no password needed

**Error log**
not necessary

**Comment by ravenclaw900** [comment]
I just fixed and pushed the statistics not showing locally. I'm not getting the same problem. In the dashboard browser console, run this and paste the output:
```js
Date.now()
JSON.parse(localStorage.tokens)[window.location.host].split('.').slice(0, 2).join('.')
```
This should remove the credential part of the token, making it safe to paste here. Also, what is the current timeout?

**Comment by JappeHallunken** [comment]
output of the command:
`syntax error near unexpected token `JSON.parse'`

You mean the set expiry time? I set it to 10 for testing.
`expiry = 10`

**Comment by JappeHallunken** [comment]
And I reinstalled nightly and the live statistics are working now again for me.

**Comment by ravenclaw900** [comment]
Please run the commands in the browser console on the dashboard page. You should be able to access it with `Ctrl + Shift + J` on Windows or `Cmd + Option + J`.

**Comment by JappeHallunken** [comment]
Sry I misunderstood you first, I obviously tried it in the browser terminal of the dashboard...

```
Date.now()
1648914245648
```
```
JSON.parse(localStorage.tokens)[window.location.host].split('.').slice(0, 2).join('.')
"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJEaWV0UGkgRGFzaGJvYXJkIiwiZXhwIjoxNjQ4OTE3NjA0fQ"
```

**Comment by ravenclaw900** [comment]
No problem, I should have been clearer. Please try updating to the latest nightly again, and if it still doesn't work, run and post the same commands.

**Comment by JappeHallunken** [comment]
Still same behaviour
```
Date.now()
1648933003032
```

```
JSON.parse(localStorage.tokens)[window.location.host].split('.').slice(0, 2).join('.')
"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJEaWV0UGkgRGFzaGJvYXJkIiwiZXhwIjoxNjQ4OTM1MTU1fQ"
```

**Comment by ravenclaw900** [comment]
Please update again (sorry), and make sure the version at the bottom is `v0.5.0-76-gf08fabe`. If it is, run the last command again, no need for the `Date.now()`.

**Comment by JappeHallunken** [comment]
This is really no problem for me!
Good news: It's working now!

Bad news:
I figured out, updating via `dietpi software reinstall 200` didn't  do the job, I had to reinstall and install again. Is this worth to open an issue at their repo?
