### ISSUE TITLE
[Bug] Sometimes "Management" kills process

### ISSUE THREAD

**Issue by MichaIng** [ravenclaw900/DietPi-Dashboard#20]
```
Nov 06 19:40:40 VM-Bullseye strace[52175]: thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: SendError(Some(Request { page: "/management", cmd: "", args: [] }))', src/sockets.rs:309:53
Nov 06 19:40:40 VM-Bullseye strace[52175]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
https://github.com/ravenclaw900/DietPi-Dashboard/blob/921913d/src/backend/src/sockets.rs#L309

Got this two times when switching from "Terminal" to "Management", but I cannot reliably replicate it, currently it works well 🤔. But probably it can be enhanced to detect and handle errors gracefully to avoid the panic. I set the `RUST_BACKTRACE=1` variable for further testing, probably it helps.

**Comment by ravenclaw900** [comment]
I can't replicate it, but I'll add some more error handling there.

**Comment by MichaIng** [comment]
Thanks, yeah I also wasn't able to replicate it after running into it two times. If it happens again, the page will now be empty, right? Good to still have a sign when the underlying issue applies, so that we can debug at a later time, and an empty page without crashing the process is a good sign 🙂.

**Comment by ravenclaw900** [comment]
If it happens (along with any other errors), It will disconnect the websocket, which will then try to reconnect, where it will (hopefully) work.

**Comment by MichaIng** [comment]
Okay, sounds best for end users. Probably fine to leave it like that. If we really want to debug, we could add some debug code/output.
