### ISSUE TITLE
The text editor showing white-on-white text when opening a file using dark mode without syntax highlighting.

### ISSUE THREAD

**Issue by atomflunder** [ravenclaw900/DietPi-Dashboard#218]
**Describe the bug**:
When you use the text editor in dark mode, the text switches from black to white, but the background of the editor stays white, creating white-on-white text which is not readable unless you highlight the text.  
Edit: Just checked and **This is only the case when not using syntax highlighting.**

**Version of DietPi-Dashboard**: 0.6.0

**Nightly or stable**: Stable

**Version of DietPi**: 8.3.1

**Device architecture**: armv8, exact device is a Raspberry Pi 4 8GB

**To Reproduce**
1. Open any file in the file browser
2. Select dark mode
3. Turn off syntax highlighting
4. Text is showing as white on the white background

**Error log**

**Additional context**
Here are a few screenshots showing what I mean:
Light mode: https://i.imgur.com/69o9Gy4.png
Dark mode: https://i.imgur.com/GYhjDbU.png
Dark mode (highlighting text): https://i.imgur.com/FJp2yms.png
Dark mode (with syntax highlighting on): https://i.imgur.com/urdEulj.png

Because dark mode was the default after installation I thought (and maybe others too) the editor was not working until I switched to light mode.

**Comment by MichaIng** [comment]
I remember the same for the notification text, e.g. update notifications. Some texts need to be excluded from the black => white color change in dark mode, or, probably better, the respective backgrounds made dark as well 🙂.

**Comment by ravenclaw900** [comment]
Fixed. The editor will now be given a dark background if needed with dark mode enabled.

**Comment by atomflunder** [comment]
Thank you for the quick fix!
