### ISSUE TITLE
Service page shows wrong service statutes for some services and some services are not shown at all

### ISSUE THREAD

**Issue by JappeHallunken** [ravenclaw900/DietPi-Dashboard#224]
Relevant services are in my case nfs-kernel-server and openvpn. They are running but showed as "exited".
papermc and transmisisom-daemon, which were stopped at the time I was checking, were not shown at all on the dashboard service page.

**Version of DietPi-Dashboard**: 0.6.0

**Nightly or stable**: Stable

**Version of DietPi**: 8.4.2

**Device architecture**: aarch64 / RPi 4

**Comment by ravenclaw900** [comment]
Hi,
Please test the nightly version, as some improvements have been made to the services page with things not showing. If it's still not working, could you post a screenshot of the page and the output of `dietpi-services status`?

**Comment by JappeHallunken** [comment]
Same with nightly build:
![dashboard1](https://user-images.githubusercontent.com/98723311/166159976-806a749b-ce15-4acf-a753-af645a9a4cc1.PNG)
![dashboard2](https://user-images.githubusercontent.com/98723311/166159978-4cc80a8e-c51d-42ba-ab85-beee6f82ca09.PNG)

**Comment by ravenclaw900** [comment]
Please post the output of the command `dietpi-services status`, with the `status` argument.

**Comment by JappeHallunken** [comment]
`DietPi-Services
─────────────────────────────────────────────────────
 Mode: status

[  OK  ] DietPi-Services | nmbd                  active (running) since Sun 2022-05-01 20:30:15 CEST; 1h 57min ago
[  OK  ] DietPi-Services | smbd                  active (running) since Sun 2022-05-01 20:30:15 CEST; 1h 57min ago
[  OK  ] DietPi-Services | nfs-kernel-server     active (exited) since Sun 2022-05-01 20:30:16 CEST; 1h 57min ago
[  OK  ] DietPi-Services | redis-server          active (running) since Sun 2022-05-01 20:30:16 CEST; 1h 57min ago
[  OK  ] DietPi-Services | mariadb               active (running) since Sun 2022-05-01 20:30:16 CEST; 1h 57min ago
[  OK  ] DietPi-Services | php7.4-fpm            active (running) since Sun 2022-05-01 20:30:17 CEST; 1h 57min ago
[  OK  ] DietPi-Services | lighttpd              active (running) since Sun 2022-05-01 20:30:17 CEST; 1h 57min ago
[  OK  ] DietPi-Services | rpimonitor            active (running) since Sun 2022-05-01 20:30:17 CEST; 1h 57min ago
[  OK  ] DietPi-Services | cron                  active (running) since Sun 2022-05-01 20:30:17 CEST; 1h 57min ago
[  OK  ] DietPi-Services | dropbear              active (running) since Tue 2022-04-19 16:25:51 CEST; 1 weeks 5 days ago
[  OK  ] DietPi-Services | openvpn               active (exited) since Tue 2022-04-19 17:09:52 CEST; 1 weeks 5 days ago
[ INFO ] DietPi-Services | dietpi-vpn            inactive (dead)
[ INFO ] DietPi-Services | dietpi-cloudshell     inactive (dead)
[  OK  ] DietPi-Services | dietpi-dashboard      active (running) since Sun 2022-05-01 22:27:56 CEST; 2s ago
[  OK  ] DietPi-Services | dietpi-ramlog         active (exited) since Tue 2022-04-19 16:25:51 CEST; 1 weeks 5 days ago
[  OK  ] DietPi-Services | dietpi-preboot        active (exited) since Tue 2022-04-19 16:25:52 CEST; 1 weeks 5 days ago
[  OK  ] DietPi-Services | dietpi-postboot       active (exited) since Tue 2022-04-19 16:25:58 CEST; 1 weeks 5 days ago
[ INFO ] DietPi-Services | dietpi-wifi-monitor   inactive (dead)`

I figured out papermc and transmission are not shown, because they are set to "excluded".
I read a little bit about the "Active: active (exited)" message and why it#s shown like that. Maybe there is a way to change this is the service webpage to prevent confusion?

**Comment by ravenclaw900** [comment]
Yeah, `exited` does sound like it's stopped. Maybe change `exited` to `active`? Or just keep it as `active (running)` and `active (exited)`. @MichaIng, thoughts?

**Comment by ravenclaw900** [comment]
Names changed in https://github.com/ravenclaw900/DietPi-Dashboard/commit/a955bddbd1aa74150240096d0f9d04304c50823a.
