### ISSUE TITLE
[Management] Update (some) data less often

### ISSUE THREAD

**Issue by MichaIng** [ravenclaw900/DietPi-Dashboard#25]
The management page currently reload all data every second. For the uptime seconds counter this makes sense, for the DietPi version, hostname, architecture not so much, and especially calling `dpkg --get-selections` every seconds to obtain the installed package count produces quite some CPU load on small SBCs. Two ideas:
1. Obtain/update values which are not expected to change regularly (basically all but uptime seconds) much less often, e.g. via internal counter to reset every X iterations and only update those on specific counter values.
2. Remove the seconds uptime counter, which doesn't seem to important when you have some days uptime, and never reload data, but only when the page itself is opened/reloaded.

The regular update of the seconds counter has the other visual side effect that the table dimensions change whenever the number of seconds changes to `0` (which hides also the "Seconds" text completely) or from one to two digits.

**Comment by ravenclaw900** [comment]
This goes for the services page too, currently it's updated every 2 seconds, for the rare occasion that you want to update the time (i.e. if it's started so recently that the time is still measured in seconds) there.

**Comment by MichaIng** [comment]
Ah totally right. There it is even more an issue since `dietpi-services` with all it's `systemctl` calls causes much higher CPU load.

Same for Processes, but there it makes sense to monitor CPU and RAM usage.

In the future we could add a live update checkbox and probably even an option for the update rate.

**Comment by ravenclaw900** [comment]
I'm probably going to change it to minutes for the management page, and not update it, and also not update the services page at all.

**Comment by MichaIng** [comment]
Sounds reasonable.
