### ISSUE TITLE
Align tokio worker thread number with CPU core number

### ISSUE THREAD

**Issue by MichaIng** [ravenclaw900/DietPi-Dashboard#26]
Currently it is hardcoded to `4`: https://github.com/ravenclaw900/DietPi-Dashboard/blob/main/src/backend/src/main.rs#L12
I'm not sure what works best here, usually I'd say that it should match the number of CPU cores. Some say core + 1 is better to always have all cores utilised even if one is waiting for I/O or so. And here the CPU usage is extremely low, so probably CPU cores * 2 is fine for better responsiveness even if multiple clients connect concurrently?

**Comment by ravenclaw900** [comment]
I think matching the number of CPUs is the default. I set that to work around a problem that, now, I think I've actually caused. I'll look into fixing it, shouldn't be too hard.

**Comment by ravenclaw900** [comment]
Alright, fixed. It uses a minimum of 2 threads, but it will scale to the number of cores.
