### ISSUE TITLE
Allow to set log level via config file

### ISSUE THREAD

**Issue by MichaIng** [ravenclaw900/DietPi-Dashboard#28]
Currently log level "info" is [hardcoded](https://github.com/ravenclaw900/DietPi-Dashboard/blob/main/src/backend/src/main.rs#L23-L27). A setting to define it via config file would be great. I see [debug messages](https://github.com/ravenclaw900/DietPi-Dashboard/blob/main/src/backend/src/main.rs#L77-L83) in the code which would be great to enable for our testing and debugging. And on the other hand for production usage, "warning" may be sufficient to reduce journal overhead.

But this is not a blocker feature at all, but of minor importance. I'll see if I can do a PR for this, but of course we should concentrate efforts on stability for now 😉.

**Comment by MichaIng** [comment]
Ah good to know. So `.with_level(log::LevelFilter::Info)` only defines the initial/default log level but is overwritten by `RUST_LOG`? This would be something we could add to our docs, e.g. adding it via override systemd config as:
```
Environment=RUST_LOG=debug
```

**Comment by ravenclaw900** [comment]
Since this can be easily fixed by environment variable, can the issue be closed?

**Comment by MichaIng** [comment]
I still think it would be good to expose this via config file. Let me try to implement this tomorrow 🙂.
