### ISSUE TITLE
Services page shows just blank

### ISSUE THREAD

**Issue by JappeHallunken** [ravenclaw900/DietPi-Dashboard#308]
I updated to latest nightly and now the services page shows the table header (Name | Status | Error Log | Start Time | Actions) but nothing else.

**Version of DietPi-Dashboard**: v0.6.0-109-ge054524

**Nightly or stable**: Nightly

**Version of DietPi**: 6.8.1

**Device architecture**: ARMv8 aarch64

**Error log** (`journalctl -u dietpi-dashboard`)
Shows nothing unusual

**Comment by ravenclaw900** [comment]
Should be fixed with https://github.com/ravenclaw900/DietPi-Dashboard/commit/a6e43d372debeb7850f4b78f61a729f265967083.

**Comment by JappeHallunken** [comment]
I've got still a blank page with `v0.6.0-111-g79e8be4`

**Comment by MichaIng** [comment]
Did you restart the service (or server)?
```sh
systemctl restart dietpi-dashboard
```

**Comment by ravenclaw900** [comment]
You need to use at least `v0.6.0-114-ga6e43d3`.
