### ISSUE TITLE
menu of urls active

### ISSUE THREAD

**Issue by moltra** [ravenclaw900/DietPi-Dashboard#337]
i would love to see a menu of urls in use.  like below that opens each programs webpage.

- deluge 192.168.0.100:8112
- samba 192.168.0.100/dietpi
- plex 192.168.0.100:32400/web

**Comment by ravenclaw900** [comment]
Indeed, this feature has been requested multiple times and will be part of the next minor release.

**Comment by MichaIng** [comment]
I'll mark this as closed. Let's keep discussion on this topic at #169.
