### ISSUE TITLE
Cannot compile from source

### ISSUE THREAD

**Issue by chunksin** [ravenclaw900/DietPi-Dashboard#340]
I'm trying to compile from source but I get an error about a missing /frontend/dist folder during compilation. Is it possible to reduce the amount of downloads also? are they all required as they take up around 1GB of disk space

**Comment by MichaIng** [comment]
> are they all required as they take up around 1GB of disk space

This cannot be changed, all dependencies are in fact in use. Next release will reduce the Rust dependencies quite a bit, but it doesn't change something on the general fact. Explicit and implicit dependencies (of `main` branch) of this project can be checked here: https://github.com/ravenclaw900/DietPi-Dashboard/network/dependencies

Not sure about the compiling error, but I remember there was something related to the recent build system switches. Please assure that you follow the instructions from the README which matches the actual version/tag you checked out, as there was a recent change: https://github.com/ravenclaw900/DietPi-Dashboard/pull/281/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5
