### ISSUE TITLE
I cannot connect to :5151

### ISSUE THREAD

**Issue by Krotosz6** [ravenclaw900/DietPi-Dashboard#354]
```
• dietpi-dashboard.service - Web Dashboard (DietPl)
Loaded: loaded (etc/systemd/si,istem/dietpl-dashboard.service; disabled; vendor preset: enabled) 
Active: failed (Result: exit-code) since Thu 2022-09-01 21:14:04 CEST; 12s ago 
Process: 1163 ExecStart=/opt/dietpi-dashboard/dietpl-dashboard (code=exited, status=1/FAILURE) 
Main PID: 1163 (code=exIted, status=1/FAILURE) 
CPU: 205ms

Sep 01 21:14:04 Odrold systemd[1]: Started Web Dashboard (DletPi). 
Sep 01 21:14:04 Odrold dietpi-dashboard[1163]: Error: Couldn't bind to [::]:5252 
Sep 01 21:14:04 Odrold dletpi-dashboard[1163]: Caused by: 
Sep 01 21:14:04 Odroid dietpi-dashboard[1163]: Address family not supported b.g protocol (os error 97)
Sep 01 21:14:04 Odroid systemd[1]: dietpi-dastboard.service: Main process exited, code=exited, status=1/FAILURE 
Sep 01 21:14:04 Odroid systemd[1]: dietpi-dashboard.service: Failed with result 'exit-code'.
```

![signal-2022-09-02-102524_002](https://user-images.githubusercontent.com/91122443/188102664-b3f37fb1-7d7d-4b5c-ad93-19ec7e20c1d6.jpeg)

**Comment by Joulinar** [comment]
Could you try to disable IPv6 and restart the service again.

**Comment by Krotosz6** [comment]
Thanks @Joulinar 
Like this? https://github.com/MichaIng/DietPi/issues/2027

**Comment by Joulinar** [comment]
No this has nothing to do with it. Just go into `dietpi-config` network settings and disable IPv6.

**Comment by Krotosz6** [comment]
Sorry. :( Buy I have only Network Options: Adapters and Network Options: Misc and I cant find disable IPv6 :(

**Comment by Joulinar** [comment]
Inside ` 7  : Network Options: Adapters`, there should be a possibility to toggle IPv6.

```
┌──────────────────────────────────────────────────┤ DietPi-Config ├───────────────────────────────────────────────────┐
│ Please select an option to change:                                                                                   │
│                                                                                                                      │
│                                                ●─ Adapter Options ──────────────●                                    │
│                                   Ethernet     : Available | [On] | Connected                                        │
│                                   WiFi         : Not Found | [Off] | Disconnected                                    │
│                                   Onboard WiFi : [Off]                                                               │
│                                                ●─ Additional Options ───────────●                                    │
│                                   IPv6         : [On]                                                                │
│                                   Proxy        : [Off]                                                               │
│                                   Test         : Run internet connection test                                        │
│                                                                                                                      │
│                                                                                                                      │
│                                  <Ok>                                      <Back>                                    │
│                                                                                                                      │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

**Comment by Krotosz6** [comment]
Unfortunately i have not. 
 
![signal-2022-09-03-212124_002](https://user-images.githubusercontent.com/91122443/188285176-f756a80e-fcde-447f-b87b-f038021ef8f1.jpeg)

**Comment by Krotosz6** [comment]
I made another fresh clean os from dietpi online installer and when it start the first boot I have recognized then ipv6 disabled because kernel failed or not accepted by kernel level. Aborting......

I have Odroid-U3 and make my DietPi from Debian Blueseye by DietPi-installer for other devices.

**Comment by Joulinar** [comment]
There is a configuration option inside `dietpi.txt`. simply switch it to 0 to disable IPv6

`CONFIG_ENABLE_IPV6=0`

**Comment by Krotosz6** [comment]
Thanks. Done. Still the same errors. Starting dashboard failed.

**Comment by Joulinar** [comment]
Can you reboot and share the log again

**Comment by Krotosz6** [comment]
The same.

• dietpi-dashboard.service - Web Dashboard (DietPl)
Loaded: loaded (ietc/systemd/si,istem/dietpl-dashboard.service; disabled; vendor preset: enabled) 
Active: failed (Result: exit-code) since Thu 2022-09-01 21:14:04 CEST; 12s ago 
Process: 1163 ENecStart=/opt/dietpi-dashboard/dietpl-dashboard (code=exited, status=1/FAILURE) 
Main PID: 1163 (code=exIted, status=1/FAILURE) 
CPU: 205ms

Sep 01 21:14:04 Odrold systemd[1]: Started Web Dashboard (DletPi). 
Sep 01 21:14:04 Odrold dietpi-dashboard[1163]: Error: Couldn't bind to [::]:5252 
Sep 01 21:14:04 Odrold dletpi-dashboard[1163]: Caused by: 
Sep 01 21:14:04 Odroid dietpi-dashboard[1163]: Address family not supported b.g protocol (os error 97)
Sep 01 21:14:04 Odroid systemd[1]: dietpi-dastboard.service: Main process exited, code=exited, status=1/FAILURE 
Sep 01 21:14:04 Odroid systemd[1]: dietpi-dashboard.service: Failed with result 'exit-code'.

**Comment by Joulinar** [comment]
are you sure the system has been rebooted? Because the error message is from September 1st. It is the same error message as shown on your initial report. Fitting exactly in date and time 😉

**Comment by Krotosz6** [comment]
I'm sure. As I wrote the errors are the same and only the details of the processor time have changed.
If it is actually necessary to paste the same log only with today's dates I will paste it later, because now I am away from home. Thank you. :)

**Comment by Krotosz6** [comment]
DietPi-Services | File viewer 

  * dietpi-dashboard-service - [Web](url) Dashboard (DietPi) 
Loaded: loaded (/etc/systemd/sustemdletpi-dashboard.service: enabled: vendor preset: enabled) 
Active: failed (Result: exit-code) since Mon 2022-09-05 09:51:93 BST: 
Process; 2275 ExecStart=/opt/dietpi-dashboard/dietpi-dashboard (code=exited, status=1/FAILURE) 
Main PID: 2275 (codes=exited, status=1/FAILURE) 
CPU: 226ms

Sep 05 09:51:32 DietPi systemd[1]: Started Web Dashboard (DletPi).
Sep 05 09:51:33 DietP dietpi-dashboard[1163]: Error: Couldn't bind to [::]:5252
Sep 05 09:51:33 DietPi dietpi-dashboard{2275) : Caused by:
Sep 05 09:51:33 DietPi dietpi-dashboard[1163]: Address family not supported b.g protocol (os error 97)
Sep 05 09:51:33 DietPi systemd[1]: dietpi-dashboard.service: Failed with result 'exit-code'.


![signal-2022-09-05-105317_002](https://user-images.githubusercontent.com/91122443/188411423-5fb90371-7b10-44a9-9ce6-6b4f0f99c812.jpeg)

**Comment by Joulinar** [comment]
I removed the screen print as it is the same information as you shared as text file. Somehow duplicate.

Your system still tried to connect to IPv6 but somehow this is not supported by your environment.

Could you try following to disable IPv6 again

```
/boot/dietpi/func/dietpi-set_hardware enableipv6 disable
```

**Comment by Krotosz6** [comment]
Ok thanks. In the meantime, I checked on my laptop on DietPi and it works.
```

 ● dietpi-dashboard.service - Web Dashboard (DietPi)                                                                  │           
          │      Loaded: loaded (/etc/systemd/system/dietpi-dashboard.service; enabled; vendor preset: enabled)                  │           
          │      Active: active (running) since Mon 2022-09-05 11:00:26 BST; 6min ago                                            │           
          │    Main PID: 1680 (dietpi-dashboar)                                                                                  │           
          │       Tasks: 10 (limit: 2321)                                                                                        │           
          │      Memory: 13.8M                                                                                                   │           
          │         CPU: 3.077s                                                                                                  │           
          │      CGroup: /system.slice/dietpi-dashboard.service                                                                  │           
          │              ├─1680 /opt/dietpi-dashboard/dietpi-dashboard                                                           │           
          │              ├─2574 /bin/login -f                                                                                    │           
          │              ├─2575 /bin/login -f                                                                                    │           
          │              ├─2585 -bash                                                                                            │           
          │              ├─2587 -bash                                                                                            │           
          │              ├─2637 /bin/bash /boot/dietpi/dietpi-launcher                                                           │           
          │              ├─2653 /bin/bash /boot/dietpi/dietpi-services                                                           │           
          │              └─2702 systemctl -l --no-pager status dietpi-dashboard                                                  │           
          │                                                                                                                      │           
          │ Sep 05 11:06:26 DietPi dietpi-dashboard[1680]:  359.460191909s  INFO                                                 │           
          │ request{remote_addr=[::ffff:192.168.0.108]:56630}: dietpi_dashboard: Request to /favicon.png                         │           
          │ Sep 05 11:06:34 DietPi dietpi-dashboard[1680]:  367.956840540s  INFO                                                 │           
          │ request{remote_addr=[::ffff:192.168.0.108]:56630}: dietpi_dashboard: Request to /login/                              │           
          │ Sep 05 11:06:39 DietPi dietpi-dashboard[1680]:  372.748729719s  INFO                                                 │           
          │ request{remote_addr=[::ffff:192.168.0.108]:56630}: dietpi_dashboard: Request to /login/                              │           
          │ Sep 05 11:06:40 DietPi dietpi-dashboard[1680]:  373.821113504s  INFO                                                 │           
          │ request{remote_addr=[::ffff:192.168.0.108]:56636}: dietpi_dashboard: Request to /ws                                  │           
          │ Sep 05 11:06:45 DietPi dietpi-dashboard[1680]:  378.542332243s  INFO                                                 │           
          │ request{remote_addr=[::ffff:192.168.0.108]:56637}: dietpi_dashboard: Request to /ws/term                             │           
          │ Sep 05 11:06:45 DietPi dietpi-dashboard[1680]:  378.554239833s  INFO                                                 │           
          │ request{remote_addr=[::ffff:192.168.0.108]:56638}: dietpi_dashboard: Request to /ws/term                             │           
          │ Sep 05 11:06:45 DietPi login[2574]: pam_unix(login:session): session opened for user root(uid=0) by (uid=0)          │           
          │ Sep 05 11:06:45 DietPi login[2585]: ROOT LOGIN  on '/dev/pts/0'                                                      │           
          │ Sep 05 11:06:45 DietPi login[2575]: pam_unix(login:session): session opened for user root(uid=0) by (uid=0)          │           
          │ Sep 05 11:06:45 DietPi login[2587]: ROOT LOGIN  on '/dev/pts/1'  
```

**Comment by Joulinar** [comment]
your issue is the Odroid-U3 as it seems not to support IPv6

**Comment by Krotosz6** [comment]
I checked on the OdroidU3 again. On the system where I had already made the change in the dietpi.txt file it said it was already disabled, and on another clean one it made the change. After reboot still the same issue.

Maybe I should change the IP port?
Or maybe I will replace dasboard to run some remote desktop.

**Comment by Joulinar** [comment]
> Maybe I should change the TCP port?
This will not change anything as your system has issues on IPv6 in general

> Or maybe I will replace dasboard to run some remote desktop.
Don't know what you mean by this

@ravenclaw900 
Would it be possible to add a switch to disable IPv6 via configuration file? Something like Unbound is doing where you could switch on/off IPv4/6 individually.

**Comment by MichaIng** [comment]
Looks like the kernel does not ship with an IPv6 module, or it is actively blacklisted. Can you check:
```sh
modinfo ipv6
find -name '*ipv6*' /lib/modules
```

Best would be if the dashboard bound to IPv6 only if it's available and enabled. But actually it does that already, isn't it? So probably this detection does not work if the kernel feature itself is missing 🤔.

**Comment by Krotosz6** [comment]
![signal-2022-09-06-165249_002](https://user-images.githubusercontent.com/91122443/188668487-cda28e79-9800-464c-a02e-51c94dcfcb38.jpeg)

**Comment by Joulinar** [comment]
correct command would be following

```
find /lib/modules/ -name '*ipv6*'
```

**Comment by MichaIng** [comment]
Ah sorry right, the path needs to be the first argument. However, not needed anymore: The IPv6 module is built into the kernel, so no dedicated module file exists. But it seems this builtin is not loaded. Probably it ia disabled via kernel cmdline or some modprobe config. Can you show the output of:
```sh
cat /proc/cmdline
grep -R ipv6 /etc/modprobe.d
```

**Comment by Krotosz6** [comment]
![signal-2022-09-07-140554_002](https://user-images.githubusercontent.com/91122443/188874369-4d1dc76f-5016-4f71-9f70-85d44ad6d07d.jpeg)

**Comment by Krotosz6** [comment]
Yes. Network connection is ok when I use it.

**Comment by MichaIng** [comment]
The last cmdline entry disables IPv6 kernel-wise. This needs to be removed. Do you know where the cmdline is set? Otherwise let's have a look into `ls -l /boot` which installs usually contains the bootloader configuration.

**Comment by Krotosz6** [comment]
Thanks for help. When we finish I would like to make a image for the others :)
![Uploading IMG_20220908_124717.jpg…]()

**Comment by MichaIng** [comment]
It uses extlinux, so `/boot/extlinux/extlinux.conf` contains the cmdline where you can remove the `ipv6.disable` part.

Mainline kernel with mainline U-Boot, that is nice to see 🙂.

**Comment by Krotosz6** [comment]
It works :D I see dashboard in network. Thanks a lot.
So now I would like to make a image for the others for OdroidU3. Is there any possibility to make this change just in clean installer image? Just remove  `ipv6.disable` fromm boot part in sd card from another PC?

**Comment by MichaIng** [comment]
The image likely has a single ext4 partition only, which cannot be mounted on Windows. Easiest would be to do this change before running the `dietpi-installer`, isn't it?

**Comment by Krotosz6** [comment]
Yup. But I have linux too. In Antix or in MXlinux could be mounted. I changed it in Antix. I have already installer version so I could try. If not, I will do like You say.

**Comment by MichaIng** [comment]
I think questions are answered? Hence closing this issue. Feel free to reopen if required.
