### ISSUE TITLE
[Request] please add cpu temperature meter

### ISSUE THREAD

**Issue by aszurnasirpal** [ravenclaw900/DietPi-Dashboard#36]
I think that one of the most important sensor that should be visualized in th system diagnostic tab should be CPU temp.

**Comment by MichaIng** [comment]
Good idea. I wonder how to implement best, I guess loading DietPi-Globals to run the `G_OBTAIN_CPU_TEMP` function in a shell is pretty overkill, though to give a precise temperature, different `/sys` tunables need to be read on every hardware. Probably there is a slim library available as Rust crate to do this with higher efficiency and same precision without invoking an external process.

**Comment by ravenclaw900** [comment]
The crate that I'm currently using to read CPU, RAM, etc has a function for that: https://docs.rs/heim/0.1.0-rc.1/heim/sensors/fn.temperatures.html.

**Comment by MichaIng** [comment]
That is great. Hopefully it is accurate on the various SBCs we support.

**Comment by ravenclaw900** [comment]
I've been trying to work on this, but I've run into some problems (https://github.com/heim-rs/heim/issues/354). Until that gets resolved, my basic changes are in the https://github.com/ravenclaw900/DietPi-Dashboard/tree/cpu-temp branch.

**Comment by ravenclaw900** [comment]
While that might work (though it doesn't on my RPi, does the `sensors` command need to be installed?), we try to use native Rust code instead of shell scripts, to keep the binary self-contained.

**Comment by MichaIng** [comment]
`apt install lm-sensors` and the (C) library is `libsensors5`.

**Comment by BeekeeperNL** [comment]
ah okay, i understand. sorry i was having trouble seeing why it was difficult to have the cpu temp seeing as it is posted each time i login via ssh. I understand now why this is not what you are trying to do, least not in this way.

**Comment by MichaIng** [comment]
Via bash shell and sourcing `/boot/dietpi/func/dietpi-globals`, there is `G_OBTAIN_CPU_TEMP` available which does the job without additional dependencies/libraries. But loading a shell + this quite large script is probably too much overhead:
```sh
bash -c '. /boot/dietpi/func/dietpi-globals; G_OBTAIN_CPU_TEMP'
```
Otherwise the logic, looping though the kernel API until a valid integer was found, could be directly implemented: https://github.com/MichaIng/DietPi/blob/4eee867/dietpi/func/dietpi-globals#L1674-L1716

**Comment by MichaIng** [comment]
Implemented already with: https://github.com/ravenclaw900/DietPi-Dashboard/pull/232
