### ISSUE TITLE
Dietpi Dashboard crash with all other services including ssh access 

### ISSUE THREAD

**Issue by lutfor-diu** [ravenclaw900/DietPi-Dashboard#405]
**Describe the bug**:

**Version of DietPi-Dashboard [v0.6.1

**Nightly or stable**: Stable

**Version of DietPi**: 8.9.2

**Device architecture**: 

**To Reproduce**

1. Go to "file explorer'
2. Click on 'click on root, mnt, and when select external flash drive folder it crashed'
3. It crashes my all dietpi system including ssh access and all other running app, terminating the access to all web service

**Error log**

Oct 22 09:58:03 DietPi dietpi-dashboard[381]:  138.068383000s  INFO request{remote_addr=[::ffff:100.78.220.16]:53351}: dietpi_dashboard: Request to /assets/dietpi.4cc58251.png
Oct 22 09:58:03 DietPi dietpi-dashboard[381]:  138.088400000s  INFO request{remote_addr=[::ffff:100.78.220.16]:53350}: dietpi_dashboard: Request to /assets/github-mark.31287333.svg
Oct 22 09:58:04 DietPi dietpi-dashboard[381]:  138.416960000s  INFO request{remote_addr=[::ffff:100.78.220.16]:54051}: dietpi_dashboard: Request to /ws
Oct 22 10:00:02 DietPi dietpi-dashboard[381]:  256.418527000s  INFO request{remote_addr=[::ffff:100.78.220.16]:53350}: dietpi_dashboard: Request to /
Oct 22 10:00:02 DietPi dietpi-dashboard[381]:  256.740132000s  INFO request{remote_addr=[::ffff:100.78.220.16]:53350}: dietpi_dashboard: Request to /assets/index.2666c94b.js
Oct 22 10:00:02 DietPi dietpi-dashboard[381]:  256.748040000s  INFO request{remote_addr=[::ffff:100.78.220.16]:53351}: dietpi_dashboard: Request to /assets/xterm.bd908267.js
Oct 22 10:00:02 DietPi dietpi-dashboard[381]:  256.752403000s  INFO request{remote_addr=[::ffff:100.78.220.16]:53364}: dietpi_dashboard: Request to /assets/index.b578e7cd.css
Oct 22 10:00:03 DietPi dietpi-dashboard[381]:  257.517893000s  INFO request{remote_addr=[::ffff:100.78.220.16]:53351}: dietpi_dashboard: Request to /assets/dietpi.4cc58251.png
Oct 22 10:00:03 DietPi dietpi-dashboard[381]:  257.535264000s  INFO request{remote_addr=[::ffff:100.78.220.16]:53350}: dietpi_dashboard: Request to /assets/github-mark.31287333.svg
Oct 22 10:00:03 DietPi dietpi-dashboard[381]:  257.619645000s  INFO request{remote_addr=[::ffff:100.78.220.16]:54826}: dietpi_dashboard: Request to /ws
root@DietPi:~# -- Journal begins at Sat 2022-10-22 09:17:03 +06, ends at Sat 2022-10-22 10:01:37 +06. --
Oct 22 09:17:21 DietPi systemd[1]: Started Web Dashboard (DietPi).
Oct 22 09:56:29 DietPi dietpi-dashboard[381]:   43.670292000s  INFO request{remote_addr=[::ffff:100.78.220.16]:53350}: dietpi_dashboard: Request to /
Oct 22 09:56:30 DietPi dietpi-dashboard[381]:   44.261730000s  INFO request{remote_addr=[::ffff:100.78.220.16]:53350}: dietpi_dashboard: Request to /assets/index.2666c94b.js
Oct 22 09:56:30 DietPi dietpi-dashboard[381]:   44.278694000s  INFO request{remote_addr=[::ffff:100.78.220.16]:53351}: dietpi_dashboard: Request to /assets/xterm.bd908267.js
Oct 22 09:56:30 DietPi dietpi-dashboard[381]:   44.846264000s  INFO request{remote_addr=[::ffff:100.78.220.16]:53364}: dietpi_dashboard: Request to /assets/index.b578e7cd.css
Oct 22 09:56:34 DietPi dietpi-dashboard[381]:   48.855215000s  INFO request{remote_addr=[::ffff:100.78.220.16]:53351}: dietpi_dashboard: Request to /assets/dietpi.4cc58251.png
Oct 22 09:56:34 DietPi dietpi-dashboard[381]:   48.862701000s  INFO request{remote_addr=[::ffff:100.78.220.16]:53350}: dietpi_dashboard: Request to /assets/github-mark.31287333.svg
Oct 22 09:56:34 DietPi dietpi-dashboard[381]:   49.04639

**Additional context**

dietpi dashboard crashed also all other service including adguard, tailscaled, qbittorrent and others.

**Comment by lutfor-diu** [comment]
Device architecture: Raspberry pi 1B, arm6

**Comment by MichaIng** [comment]
Is it possibly not crashing but hanging for 90 seconds? Is it the same when you access the same mount point via SSH (or local console), and/or when you use the dashboard's terminal?

**Comment by lutfor-diu** [comment]
> Is it possibly not crashing but hanging for 90 seconds? Is it the same when you access the same mount point via SSH (or local console), and/or when you use the dashboard's terminal?

no hanging, i thing it just unresponsive and i had to manually reboot the Pi by turning of the power source.
i access same mount point via ssh using putty, no crash. 
yes, also happen when using dashboard terminal -> change to another tab and return to terminal.

**Comment by MichaIng** [comment]
Can you trigger the issue while having an SSH session open with this command running:
```sh
journalctl -fn 0
```
Probably we see some related system/kernel logs. Currently I've no idea how the dashboard would gather information from within a mount point (file list and such) differently, especially when you use the terminal feature instead of the file browser, so that a crash would happen.

**Comment by lutfor-diu** [comment]
> Can you trigger the issue while having an SSH session open with this command running:
> 
> ```shell
> journalctl -fn 0
> ```
> 
> Probably we see some related system/kernel logs. Currently I've no idea how the dashboard would gather information from within a mount point (file list and such) differently, especially when you use the terminal feature instead of the file browser, so that a crash would happen.


-- Journal begins at Sat 2022-10-22 10:17:03 +06. --
Oct 22 21:51:43 DietPi dietpi-dashboard[334]: 39126.835258000s  INFO request{rem                              ote_addr=[::ffff:192.168.31.70]:55816}: dietpi_dashboard: Request to /
Oct 22 21:51:43 DietPi dietpi-dashboard[334]: 39127.065874000s  INFO request{rem                              ote_addr=[::ffff:192.168.31.70]:55816}: dietpi_dashboard: Request to /assets/ind                              ex.2666c94b.js
Oct 22 21:51:43 DietPi dietpi-dashboard[334]: 39127.074894000s  INFO request{rem                              ote_addr=[::ffff:192.168.31.70]:55815}: dietpi_dashboard: Request to /assets/xte                              rm.bd908267.js
Oct 22 21:51:43 DietPi dietpi-dashboard[334]: 39127.087289000s  INFO request{rem                              ote_addr=[::ffff:192.168.31.70]:55817}: dietpi_dashboard: Request to /assets/ind                              ex.b578e7cd.css
Oct 22 21:51:44 DietPi dietpi-dashboard[334]: 39127.315917000s  INFO request{rem                              ote_addr=[::ffff:192.168.31.70]:55819}: dietpi_dashboard: Request to /ws
Oct 22 21:51:44 DietPi dietpi-dashboard[334]: 39127.327045000s  INFO request{rem                              ote_addr=[::ffff:192.168.31.70]:55817}: dietpi_dashboard: Request to /assets/die                              tpi.4cc58251.png
Oct 22 21:51:44 DietPi dietpi-dashboard[334]: 39127.330500000s  INFO request{rem                              ote_addr=[::ffff:192.168.31.70]:55815}: dietpi_dashboard: Request to /assets/git                              hub-mark.31287333.svg
Oct 22 21:51:49 DietPi dietpi-dashboard[334]: 39132.484196000s  INFO request{rem                              ote_addr=[::ffff:192.168.31.70]:55817}: dietpi_dashboard: Request to /login/
Oct 22 21:51:50 DietPi dietpi-dashboard[334]: 39133.523516000s  INFO request{rem                              ote_addr=[::ffff:192.168.31.70]:55826}: dietpi_dashboard: Request to /ws
Oct 22 21:52:00 DietPi dietpi-dashboard[334]: 39143.652561000s  INFO request{rem                              ote_addr=[::ffff:192.168.31.70]:55854}: dietpi_dashboard: Request to /ws/term
Oct 22 21:52:00 DietPi dietpi-dashboard[334]: 39143.695269000s  INFO request{rem                              ote_addr=[::ffff:192.168.31.70]:55855}: dietpi_dashboard: Request to /ws/term
Oct 22 21:52:00 DietPi login[4446]: pam_unix(login:session): session opened for                               user root(uid=0) by (uid=0)
Oct 22 21:52:00 DietPi login[4448]: pam_unix(login:session): session opened for                               user root(uid=0) by (uid=0)
Oct 22 21:52:00 DietPi login[4459]: ROOT LOGIN  on '/dev/pts/1'
Oct 22 21:52:00 DietPi login[4458]: ROOT LOGIN  on '/dev/pts/2'
Oct 22 21:52:11 DietPi login[4448]: pam_unix(login:session): session closed for                               user root
Oct 22 21:52:11 DietPi dietpi-dashboard[334]: 39154.938782000s  INFO request{rem                              ote_addr=[::ffff:192.168.31.70]:55855}:term_handler: dietpi_dashboard::socket_ha                              ndlers: Closed terminal
Oct 22 21:52:11 DietPi dietpi-dashboard[334]: 39154.965541000s  INFO request{rem                              ote_addr=[::ffff:192.168.31.70]:55867}: dietpi_dashboard: Request to /ws/file
Oct 22 21:52:20 DietPi dietpi-dashboard[334]: memory allocation of 1647312896 by                              tes failed
Oct 22 21:52:20 DietPi login[4446]: pam_unix(login:session): session closed for                               user root
Oct 22 21:52:20 DietPi systemd[1]: dietpi-dashboard.service: Main process exited                              , code=killed, status=6/ABRT
Oct 22 21:52:20 DietPi systemd[1]: dietpi-dashboard.service: Failed with result                               'signal'.
Oct 22 21:52:20 DietPi systemd[1]: dietpi-dashboard.service: Consumed 4.085s CPU                               time.
Oct 22 21:52:45 DietPi filebrowser[3818]: 2022/10/22 21:52:45 /api/renew: 401 19                              2.168.31.70 <nil>
Oct 22 21:53:08 DietPi tailscaled[355]: dns: resolver: forward: recv: response c                              ode indicating server failure: 2
Oct 22 21:53:08 DietPi tailscaled[355]: dns udp query: response code indicates s                              erver issue
Oct 22 21:53:13 DietPi tailscaled[355]: dns: resolver: forward: recv: response c                              ode indicating server failure: 2
Oct 22 21:53:13 DietPi tailscaled[355]: dns udp query: response code indicates s                              erver issue
Oct 22 21:53:21 DietPi tailscaled[355]: dns: resolver: forward: recv: response c                              ode indicating server failure: 2
Oct 22 21:53:21 DietPi tailscaled[355]: dns udp query: response code indicates s                              erver issue
Oct 22 21:53:26 DietPi tailscaled[355]: dns: resolver: forward: recv: response c                              ode indicating server failure: 2
Oct 22 21:53:26 DietPi tailscaled[355]: dns udp query: response code indicates s                              erver issue

**Comment by lutfor-diu** [comment]
> **Describe the bug**:
> 
> **Version of DietPi-Dashboard [v0.6.1
> 
> **Nightly or stable**: Stable
> 
> **Version of DietPi**: 8.9.2
> 
> **Device architecture**:
> 
> **To Reproduce**
> 
> 1. Go to "file explorer'
> 2. Click on 'click on root, mnt, and when select external flash drive folder it crashed'
> 3. It crashes my all dietpi system including ssh access and all other running app, terminating the access to all web service
> 
> **Error log**
> 
> Oct 22 09:58:03 DietPi dietpi-dashboard[381]: 138.068383000s INFO request{remote_addr=[::ffff:100.78.220.16]:53351}: dietpi_dashboard: Request to /assets/dietpi.4cc58251.png Oct 22 09:58:03 DietPi dietpi-dashboard[381]: 138.088400000s INFO request{remote_addr=[::ffff:100.78.220.16]:53350}: dietpi_dashboard: Request to /assets/github-mark.31287333.svg Oct 22 09:58:04 DietPi dietpi-dashboard[381]: 138.416960000s INFO request{remote_addr=[::ffff:100.78.220.16]:54051}: dietpi_dashboard: Request to /ws Oct 22 10:00:02 DietPi dietpi-dashboard[381]: 256.418527000s INFO request{remote_addr=[::ffff:100.78.220.16]:53350}: dietpi_dashboard: Request to / Oct 22 10:00:02 DietPi dietpi-dashboard[381]: 256.740132000s INFO request{remote_addr=[::ffff:100.78.220.16]:53350}: dietpi_dashboard: Request to /assets/index.2666c94b.js Oct 22 10:00:02 DietPi dietpi-dashboard[381]: 256.748040000s INFO request{remote_addr=[::ffff:100.78.220.16]:53351}: dietpi_dashboard: Request to /assets/xterm.bd908267.js Oct 22 10:00:02 DietPi dietpi-dashboard[381]: 256.752403000s INFO request{remote_addr=[::ffff:100.78.220.16]:53364}: dietpi_dashboard: Request to /assets/index.b578e7cd.css Oct 22 10:00:03 DietPi dietpi-dashboard[381]: 257.517893000s INFO request{remote_addr=[::ffff:100.78.220.16]:53351}: dietpi_dashboard: Request to /assets/dietpi.4cc58251.png Oct 22 10:00:03 DietPi dietpi-dashboard[381]: 257.535264000s INFO request{remote_addr=[::ffff:100.78.220.16]:53350}: dietpi_dashboard: Request to /assets/github-mark.31287333.svg Oct 22 10:00:03 DietPi dietpi-dashboard[381]: 257.619645000s INFO request{remote_addr=[::ffff:100.78.220.16]:54826}: dietpi_dashboard: Request to /ws root@DietPi:~# -- Journal begins at Sat 2022-10-22 09:17:03 +06, ends at Sat 2022-10-22 10:01:37 +06. -- Oct 22 09:17:21 DietPi systemd[1]: Started Web Dashboard (DietPi). Oct 22 09:56:29 DietPi dietpi-dashboard[381]: 43.670292000s INFO request{remote_addr=[::ffff:100.78.220.16]:53350}: dietpi_dashboard: Request to / Oct 22 09:56:30 DietPi dietpi-dashboard[381]: 44.261730000s INFO request{remote_addr=[::ffff:100.78.220.16]:53350}: dietpi_dashboard: Request to /assets/index.2666c94b.js Oct 22 09:56:30 DietPi dietpi-dashboard[381]: 44.278694000s INFO request{remote_addr=[::ffff:100.78.220.16]:53351}: dietpi_dashboard: Request to /assets/xterm.bd908267.js Oct 22 09:56:30 DietPi dietpi-dashboard[381]: 44.846264000s INFO request{remote_addr=[::ffff:100.78.220.16]:53364}: dietpi_dashboard: Request to /assets/index.b578e7cd.css Oct 22 09:56:34 DietPi dietpi-dashboard[381]: 48.855215000s INFO request{remote_addr=[::ffff:100.78.220.16]:53351}: dietpi_dashboard: Request to /assets/dietpi.4cc58251.png Oct 22 09:56:34 DietPi dietpi-dashboard[381]: 48.862701000s INFO request{remote_addr=[::ffff:100.78.220.16]:53350}: dietpi_dashboard: Request to /assets/github-mark.31287333.svg Oct 22 09:56:34 DietPi dietpi-dashboard[381]: 49.04639
> 
> **Additional context**
> 
> dietpi dashboard crashed also all other service including adguard, tailscaled, qbittorrent and others.

i was accessing dietpi using tailscale, and this happen. but when tried to replicate this same scenario from local network, only dashboard crash and hang. other services were accessible.

**Comment by MichaIng** [comment]
> Oct 22 21:52:20 DietPi dietpi-dashboard[334]: memory allocation of 1647312896 bytes failed

It tries to allocate 1.5 GiB memory 🤔. Does this match the space is used on this drive or by the largest file in its root or so? Depending on other services memory usage, they are then OOM killed by the kernel.

This happens in the file handler. Currently not sure whether this is supposed when selecting a directory: https://github.com/ravenclaw900/DietPi-Dashboard/blob/5076e21/src/socket_handlers.rs#L434

Can you retry with debug logs enabled:
```sh
G_CONFIG_INJECT 'log_level[[:blank:]]' '#log_level = "debug"' /opt/dietpi-dashboard/config.toml
systemctl restart dietpi-dashboard
```

Pinging also @ravenclaw900 who might find out better why this memory allocation is done. Probably it for some reason tries to serve the whole directory as download or so?

**Comment by ravenclaw900** [comment]
The only reason listing a directory could fail is if there are a really large number of files in the folder being listed. In your case, it would have to be over 14 million files. How many files are in the folder? 
```
cd /mnt/whatever
ls -a | wc -l
```

**Comment by lutfor-diu** [comment]
> > Oct 22 21:52:20 DietPi dietpi-dashboard[334]: memory allocation of 1647312896 bytes failed
> 
> It tries to allocate 1.5 GiB memory 🤔. Does this match the space is used on this drive or by the largest file in its root or so? Depending on other services memory usage, they are then OOM killed by the kernel.
> 
> This happens in the file handler. Currently not sure whether this is supposed when selecting a directory: https://github.com/ravenclaw900/DietPi-Dashboard/blob/5076e21/src/socket_handlers.rs#L434
> 
> Can you retry with debug logs enabled:
> 
> ```shell
> G_CONFIG_INJECT 'log_level[[:blank:]]' '#log_level = "debug"' /opt/dietpi-dashboard/config.toml
> systemctl restart dietpi-dashboard
> ```
> 
> Pinging also @ravenclaw900 who might find out better why this memory allocation is done. Probably it for some reason tries to serve the whole directory as download or so?

i have some big file and movie in that file. all together not crossing 100 items.

**Comment by lutfor-diu** [comment]
> The only reason listing a directory could fail is if there are a really large number of files in the folder being listed. In your case, it would have to be over 14 million files. This seems unreasonable, so the problem is probably somewhere else, but let's check anyway. How many files are in the folder?
> 
> ```
> cd /mnt/whatever
> ls -A | wc -l
> ```

i have some big file and movie in that file. all together not crossing 100 items.

**Comment by lutfor-diu** [comment]
ls -A | wc -l
9

**Comment by ravenclaw900** [comment]
Please post the crash log again with debug logging enabled.

**Comment by MichaIng** [comment]
This commit might have fixed it: https://github.com/ravenclaw900/DietPi-Dashboard/commit/75c2938
E. g. a swap file was completely read into memory, easily causing a OOM crash. But test to test with nightly build.

**Comment by ravenclaw900** [comment]
Closing due to probable fix. Please reopen if there are still any issues.
