### ISSUE TITLE
temp_unit missing quotes in default config.toml

### ISSUE THREAD

**Issue by chumbazoid** [ravenclaw900/DietPi-Dashboard#426]
**Describe the bug**:
In config.toml, `temp_unit` requires quotes around the desired value, but quotes are not present in the default file:
```
# Preferred temperature unit
# - Options: fahrenheit, celsius
# - Default: celsius
#temp_unit = celsius
```
Removing the comment hash in front of `temp_unit` will result in DietPi-Dashboard failing to start. This is confusing when seeking to set for Fahrenheit, especially since other values requiring quoted strings are correctly formatted in the examples given in the default config file.

Default config.toml should be updated to read:
```
#temp_unit = "celsius"
```

DietPi-Dashboard works as expected when the quotes are present.

**Version of DietPi-Dashboard**: 0.6.1

**Version of DietPi**: 8.1.0

**Device architecture**: ARMv8 / RPi4

**Error log**

> dietpi-dashboard[2599]: thread 'main' panicked at 'Error reading config: Error { tag: Tag(Default, 2), profile: Some(Profile(Uncased { string: "default" })), metadata: Some(Metadata { name: "TOML file", source: Some(File("/opt/dietpi-dashboard/config.toml")), provide_location: Some(Location { file: "src/config.rs", line: 65, col: 10 }), interpolater:  }), path: [], kind: Message("invalid TOML value, did you mean to use a quoted string? at line 46 column 13"), prev: None }', src/config.rs:68:10

**Comment by MichaIng** [comment]
Many thanks for your report.

Indeed, strings need to be double-quoted. Fix is up: #427
