### ISSUE TITLE
Request - Add multiple node dashboard

### ISSUE THREAD

**Issue by Yfksw65** [ravenclaw900/DietPi-Dashboard#43]
Hello

An interesting feature would be to be able to manage several dietpi hosts from the same page.

thank you for your work

**Comment by MichaIng** [comment]
Many thanks for your request.

Interesting idea. Probably it is not even that difficult to implement. The frontend of the host would need to communicate with the backend socket of another dashboard instance. I'm not sure currently how strict frontend and backend are separated, i.e. whether the frontend itself obtains some system info as well independently. A backend-only install option which provides the backend API only would then be a consequent addition, in a way that it can be restricted to be accessible e.g. only from within the same LAN or from a specific IP (IP/subnet binding). So you need to forward and secure only a single system's web frontend and can access all DietPi systems within the same LAN. When we implement authentication/password protection, additional credentials would then need to be stored and passed by the frontend when accessing a remote backend.

**Comment by TommySharpNZ** [comment]
Great idea!

**Comment by ravenclaw900** [comment]
The basic infrastructure for this is on the backend-only branch. It only has the websocket handlers and the login page.

**Comment by MichaIng** [comment]
I learned that while trying to implement dark/light mode switch via config file. So this means in theory it would be possible to connect to a backend on another host, simply by adding the host/IP to all backend API requests. The remote instances could then have the backend installed only.

The versions of course need to match, or we'd need to define which (backend) features are available on which version and show/hide/adjust respective elements in the frontends to enable compatibility with a range of backend versions. And the backend then as well needs to be backwards compatible 🙄. But I think that is overkill and breaks the idea of having it lightweight and also maintainable. Shouldn't be an issue to keep the multiple instances in version sync, as the installation/update is very quick.

**Comment by ravenclaw900** [comment]
We could also have it send a version string with the other "global"s, and check if it is semver-compatible. This will really only work once the dashboard gets out of 0.x, though.

**Comment by MichaIng** [comment]
Good idea, makes sense to rule out running into issues. When the API gets more stable, we could also take semantic versioning by its word and break compatibility only with major version increments, so that all subversions are compatible with each other. New backend features can still be added with subversions, they simply won't be used by an older frontend.

**Comment by Joulinar** [comment]
Would that mean to split frontend and backend into 2 different packages that could be installed separately?

**Comment by ravenclaw900** [comment]
Currently, in the backend-only branch, I've added a 'feature' for the frontend, which when disabled by building with `--no-default-features` doesn't include or serve any of the frontend files.

**Comment by MichaIng** [comment]
> Would that mean to split frontend and backend into 2 different packages that could be installed separately?

This is not mandatory for remote backend access to work, but it definitely makes sense to have a lighter backend-only instance, and it is at least less obvious/trivial for harmful clients to access the backend API directly compared to having a regular frontend login mask.

**Comment by wsimon98** [comment]
Being able to view different PIs from the one interface, and install/uninstall software would be SO helpful in my environment. I run multiple instances of PI on VMs through ProxMox for various services and replication reasons.

**Comment by C-Fu** [comment]
Only reason I still use portainer and webmin is because of the multinode feature. Can't wait to ditch them for this!

**Comment by Joulinar** [comment]
Portainer is a tool to manage Docker container. A function the Daschboard did not have.
