### ISSUE TITLE
[Visual] Lock the aspect ratio of charts?

### ISSUE THREAD

**Issue by TommySharpNZ** [ravenclaw900/DietPi-Dashboard#47]
Would be good to lock the aspect ratio so charts are not overly tall like this?
![image](https://user-images.githubusercontent.com/15130284/142557775-ddf1b250-b997-4c74-a304-3a9178017519.png)

**Comment by ravenclaw900** [comment]
Currently, the chart grows and shrinks as the page is resized. If the aspect ratio was locked, it would still (kind of) resize, but it would be a small square at the top of the card. Personally, that doesn't seem very visually appealing to me, but I might be wrong.

**Comment by TommySharpNZ** [comment]
On a portrait monitor it looks way too tall. Chart width growing is good, but maybe the height should be locked to a 16:9 ration kinda like a TV? So not saying lock them to a specific pixel height.... Just a ration of what the width is...

**Comment by MichaIng** [comment]
An alternative would be to show diagram and bars below each other instead of aside each other, if container height > width, so the diagram is wider and the height of the screen is used more effectively. On top of that, if still necessary, the diagram could be given a minimum width:height ratio of e.g. 0.5, so that the height is capped if it would exceed two times the width.

**Comment by ravenclaw900** [comment]
I also have it going horizontally on smaller screens, that would probably look good on larger screens too.

**Comment by ravenclaw900** [comment]
@TommySharpNZ, please test the latest nightly.

**Comment by TommySharpNZ** [comment]
I think I chose not to use the nightly builds when I installed the dashboard.... Is it best to uninstall and re-install?

**Comment by Joulinar** [comment]
Could you try to reinstall

`dietpi-software reinstall 200`

**Comment by TommySharpNZ** [comment]
Okay, did an uninstall/reinstall.... Charts look a bit different on my tall monitor now but don't fit properly on the screen.
![image](https://user-images.githubusercontent.com/15130284/143090802-8a68d5c4-1fd2-4ab1-a503-76b39c72d678.png)

**Comment by TommySharpNZ** [comment]
On a phone sized screen the chart is also too tall....The aspect ratio ideally needs to be locked so that the chart is always 4:3 or 16:9 maybe...
![image](https://user-images.githubusercontent.com/15130284/143091179-2fb51497-7133-4b61-b7fc-c5171621e49e.png)

**Comment by MichaIng** [comment]
Looks like the dimensions are not correctly calculated to fit the browser window without scrolling. Probably some margin is not respected, and/or the top bar and left menu? Also, the `DietPi-Dashboard` text does not fit. Not sure whether we could move it into the top bar, or whether then on horizontal screens this collates with the icon, or switch icon and text?

Generally I think it's fine to not have a fixed aspect ratio, as then the figures might become very small. Adjusting to screen/window to make use of the available size sounds reasonable. But we could add some caps to avoid at least a too high diagram, like mentioned above, 1:2 at max or so.

**Comment by ravenclaw900** [comment]
If the screen were any smaller, the DietPi-Dashboard text would be hidden. Anyway, I've changed it to have a different "base"  size on mobile devices, which should fix it being too tall and going off the screen.

**Comment by TommySharpNZ** [comment]
Seems to behave a lot better now across the different screen sizes! :-)

**Comment by ravenclaw900** [comment]
Great! Can this be closed, then?

**Comment by TommySharpNZ** [comment]
Yeah I think so....
