### ISSUE TITLE
Request : 2 tables on the Software tab

### ISSUE THREAD

**Issue by TommySharpNZ** [ravenclaw900/DietPi-Dashboard#48]
I think having 2 separate tables on the Software page would work better. The first table would just be installed software and the second table would be available software. This would make for a better user experience...

**Comment by ravenclaw900** [comment]
This doesn't seem like a bad idea. How about 2 tabs, which switch between the tables? That would also remove the need to have to stop people from installing and uninstalling at the same time.

**Comment by TommySharpNZ** [comment]
Yup, 2 tabs just as good if not better :-)

**Comment by MichaIng** [comment]
> remove the need to have to stop people from installing and uninstalling at the same time

I just stumbled above this issue. So yes two tabs sound like a sane solution so one can either deselect installed software or select not installed software only, not mixing both.
