### ISSUE TITLE
dietpi-dashboard.service: Failed with result 'signal'.

### ISSUE THREAD

**Issue by eddydc** [ravenclaw900/DietPi-Dashboard#488]
**Describe the bug**:
I wanted to try out the dashboard and installed it. 

All seems to have been installed properly

Step: Install completed
```
[  OK  ] DietPi-Survey | Purging survey data
[ SUB1 ] DietPi-Services > restart
[  OK  ] DietPi-Services | restart : php8.2-fpm
[  OK  ] DietPi-Services | restart : lighttpd
[  OK  ] DietPi-Services | restart : cron
[ INFO ] DietPi-Software | Starting installed services, not controlled by DietPi-Services
[  OK  ] DietPi-Software | systemctl enable dietpi-dashboard
[  OK  ] DietPi-Software | systemctl start dietpi-dashboard
```

but the browser can't connect to it.

When I do
`systemctl status dietpi-dashboard`

I get 
```
× dietpi-dashboard.service - Web Dashboard (DietPi)
     Loaded: loaded (/etc/systemd/system/dietpi-dashboard.service; enabled; preset: enabled)
     Active: failed (Result: signal) since Sun 2023-01-29 09:57:04 CET; 4s ago
   Duration: 107ms
    Process: 42531 ExecStart=/opt/dietpi-dashboard/dietpi-dashboard (code=killed, signal=SEGV)
   Main PID: 42531 (code=killed, signal=SEGV)
        CPU: 93ms

Jan 29 09:57:04 Pi-hole systemd[1]: Started Web Dashboard (DietPi).
Jan 29 09:57:04 Pi-hole systemd[1]: dietpi-dashboard.service: Main process exited, code=killed, status=11/SEGV
Jan 29 09:57:04 Pi-hole systemd[1]: dietpi-dashboard.service: Failed with result 'signal'.
```

**Version of DietPi-Dashboard**: v0.6.1

Stable

DietPi v8.13.2 

x86_64 on proxmox

**To Reproduce**
Installation via dietpi-software

**Error log**
```
journalctl -u dietpi-dashboard
Jan 29 09:42:20 Pi-hole systemd[1]: Started Web Dashboard (DietPi).
Jan 29 09:42:20 Pi-hole systemd[1]: dietpi-dashboard.service: Main process exited, code=killed, status=11/SEGV
Jan 29 09:42:20 Pi-hole systemd[1]: dietpi-dashboard.service: Failed with result 'signal'.
Jan 29 09:50:23 Pi-hole systemd[1]: Started Web Dashboard (DietPi).
Jan 29 09:50:23 Pi-hole systemd[1]: dietpi-dashboard.service: Main process exited, code=killed, status=11/SEGV
Jan 29 09:50:23 Pi-hole systemd[1]: dietpi-dashboard.service: Failed with result 'signal'.
Jan 29 09:57:04 Pi-hole systemd[1]: Started Web Dashboard (DietPi).
Jan 29 09:57:04 Pi-hole systemd[1]: dietpi-dashboard.service: Main process exited, code=killed, status=11/SEGV
Jan 29 09:57:04 Pi-hole systemd[1]: dietpi-dashboard.service: Failed with result 'signal'.
```

**Comment by Joulinar** [comment]
can you share some more system details pls

#### Required 
- DietPi version | `cat /boot/dietpi/.version`
- Distro version | `echo $G_DISTRO_NAME $G_RASPBIAN`
- Kernel version | `uname -a`
- SBC model | `echo $G_HW_MODEL_NAME` or (EG: RPi3)
- Power supply used | (EG: 5V 1A RAVpower)
- SDcard used | (EG: SanDisk ultra)

As well, did you tried the nightly build.

**Comment by eddydc** [comment]
Hi,
Here is the requested info
cat /boot/dietpi/.version
G_DIETPI_VERSION_CORE=8
G_DIETPI_VERSION_SUB=13
G_DIETPI_VERSION_RC=2
G_GITBRANCH='master'
G_GITOWNER='MichaIng'
G_LIVE_PATCH_STATUS[0]='applied'
G_LIVE_PATCH_STATUS[1]='applied'

echo $G_DISTRO_NAME $G_RASPBIAN
bookworm

uname -a
Linux AdGuard 6.1.0-1-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.4-1 (2023-01-07) x86_64 GNU/Linux

Didn't try the nightly build yet, since I'm not so keen on using those versions. But if you want me to, I will make an exception

Cheers,
Eddy

**Comment by Joulinar** [comment]
Just give it a try. You are not able to damage anything. Maybe the issue is related to Debian Bookworm 🤔

**Comment by eddydc** [comment]
The nightly version seems to work.

**Comment by ravenclaw900** [comment]
Glad that the nightly works, but it's weird that the dashboard is crashing with a segmentation fault immediately. This kind of goes against the whole purpose of writing it in Rust (memory safety is a major selling point), but maybe the issue is something different. Did `dmesg` show any errors?
```
dmesg -l emerg,alert,crit,err,warn
```

**Comment by eddydc** [comment]
No idea what it means (I'm not an expert), but it gives this:
dmesg -l emerg,alert,crit,err,warn
[    0.704824] shpchp 0000:05:01.0: pci_hp_register failed with error -16
[    0.705160] shpchp 0000:05:01.0: Slot initialization failed
[    0.709694] shpchp 0000:05:02.0: pci_hp_register failed with error -16
[    0.710028] shpchp 0000:05:02.0: Slot initialization failed
[    0.713898] shpchp 0000:05:03.0: pci_hp_register failed with error -16
[    0.714232] shpchp 0000:05:03.0: Slot initialization failed
[    0.718768] shpchp 0000:05:04.0: pci_hp_register failed with error -16
[    0.719105] shpchp 0000:05:04.0: Slot initialization failed
[    1.104273] sd 0:0:0:0: Power-on or device reset occurred
[    3.004183] snd_hda_intel 0000:00:1b.0: no codecs found!

**Comment by ravenclaw900** [comment]
Nothing there. Could you try `dmesg | grep segfault`?

**Comment by eddydc** [comment]
More result:
 dmesg | grep segfault
[162213.258639] dietpi-dashboar[40521]: segfault at 7f800338d170 ip 00007f800338d170 sp 00007ffe7f645738 error 14 likely on CPU 0 (core 0, socket 0)
[162695.643376] dietpi-dashboar[41506]: segfault at 7fde83f05170 ip 00007fde83f05170 sp 00007ffcf2f351b8 error 14 likely on CPU 0 (core 0, socket 0)
[163096.449395] dietpi-dashboar[42531]: segfault at 7f3e44367170 ip 00007f3e44367170 sp 00007fffb6f04df8 error 14 likely on CPU 0 (core 0, socket 0)
Hopefully, you can make something about it.

**Comment by ravenclaw900** [comment]
If you still have the old (stable) version of the dashboard, could you try running it manually?
```
/path/to/dietpi-dashboard
```

**Comment by Joulinar** [comment]
I'm able to replicate the behavior 

```
root@DietPiVM4:~# journalctl -u dietpi-dashboard
Jan 29 17:39:51 DietPiVM4 systemd[1]: Started Web Dashboard (DietPi).
Jan 29 17:39:51 DietPiVM4 systemd[1]: dietpi-dashboard.service: Main process exited, code=killed, status=11/SEGV
Jan 29 17:39:51 DietPiVM4 systemd[1]: dietpi-dashboard.service: Failed with result 'signal'.
root@DietPiVM4:~#
```

```
root@DietPiVM4:~# /opt/dietpi-dashboard/dietpi-dashboard
Segmentation fault
root@DietPiVM4:~#
```

```
root@DietPiVM4:~# dmesg | grep segfault
[  236.284238] dietpi-dashboar[1456]: segfault at 7fa7abf26170 ip 00007fa7abf26170 sp 00007fff161201b8 error 14 likely on CPU 0 (core 0, socket 0)
[  720.602434] dietpi-dashboar[1478]: segfault at 7f8afb4a1170 ip 00007f8afb4a1170 sp 00007ffefb5a3448 error 14 likely on CPU 0 (core 0, socket 0)
root@DietPiVM4:~#
```

**Comment by eddydc** [comment]
I can confirm the above
/opt/dietpi-dashboard/dietpi-dashboard
Segmentation fault
dmesg | grep segfault
[162213.258639] dietpi-dashboar[40521]: segfault at 7f800338d170 ip 00007f800338d170 sp 00007ffe7f645738 error 14 likely on CPU 0 (core 0, socket 0)
[162695.643376] dietpi-dashboar[41506]: segfault at 7fde83f05170 ip 00007fde83f05170 sp 00007ffcf2f351b8 error 14 likely on CPU 0 (core 0, socket 0)
[163096.449395] dietpi-dashboar[42531]: segfault at 7f3e44367170 ip 00007f3e44367170 sp 00007fffb6f04df8 error 14 likely on CPU 0 (core 0, socket 0)
[193251.038451] dietpi-dashboar[45451]: segfault at 7f37ae54a170 ip 00007f37ae54a170 sp 00007ffd24d86878 error 14 likely on CPU 0 (core 0, socket 0)

**Comment by ravenclaw900** [comment]
Shoot, it was the `upx` compression. Recompressed and reuploaded to the release, could you test now?

**Comment by eddydc** [comment]
It works perfectly. Many thanks for the quick fix. Really appreciated

**Comment by Joulinar** [comment]
logging good now

```
root@DietPiVM4:~# systemctl status dietpi-dashboard
● dietpi-dashboard.service - Web Dashboard (DietPi)
     Loaded: loaded (/etc/systemd/system/dietpi-dashboard.service; enabled; preset: enabled)
     Active: active (running) since Sun 2023-01-29 20:51:21 CET; 20s ago
   Main PID: 1459 (dietpi-dashboar)
      Tasks: 1 (limit: 2358)
     Memory: 3.0M
        CPU: 160ms
     CGroup: /system.slice/dietpi-dashboard.service
             └─1459 /opt/dietpi-dashboard/dietpi-dashboard

Jan 29 20:51:21 DietPiVM4 systemd[1]: Started Web Dashboard (DietPi).
root@DietPiVM4:~#
```

**Comment by ravenclaw900** [comment]
Strange that this wasn't caught earlier. Even stranger is I know that I tested these binaries before release. Maybe UPX used some strange behavior that was fixed between release and now. Regardless, the problem is solved, so can the issue be closed?

**Comment by eddydc** [comment]
No worries. The most important is that it got fixed and really quick.
