### ISSUE TITLE
[Request] Shortcuts to any installed web services?

### ISSUE THREAD

**Issue by TommySharpNZ** [ravenclaw900/DietPi-Dashboard#49]
This is very much a "nice to have" but would be super cool if any installed software that has a web UI can be listed on the main page as little shortcuts that can be clicked. Something along the lines of what Heimdall looks like?

https://github.com/linuxserver/Heimdall

![image](https://user-images.githubusercontent.com/15130284/142560099-28fb45a1-4c29-4135-a9fa-42261536c133.png)

**Comment by GvY85** [comment]
I like the idea, that way the dashboard is your gateway to all installed services.

**Comment by ravenclaw900** [comment]
This definitely looks like a nice to have feature, but using Heimdall itself is probably a better option. After all, that's what it's meant for!

**Comment by ravenclaw900** [comment]
Closing in favor of the more detailed https://github.com/ravenclaw900/DietPi-Dashboard/issues/169.
