### ISSUE TITLE
RISC-V builds/support

### ISSUE THREAD

**Issue by MichaIng** [ravenclaw900/DietPi-Dashboard#503]
As we added RISC-V support (very experimental, of course) and are testing with a first SBC: StarFive VisionFive 2

**Comment by ravenclaw900** [comment]
Looks like cross-compilation can be done with the `riscv64gc-unknown-linux-gnu` target fairly easily (of course I still haven't tested it).

**Comment by MichaIng** [comment]
I thought so as well, a single line in the workflow.
