### ISSUE TITLE
Incorrect software documentation link: Homer

### ISSUE THREAD

**Issue by holocronology** [ravenclaw900/DietPi-Dashboard#512]
**Describe the bug**:
Link for HOMER documentation is incorrect on software page.
Current link: https://dietpi.com/docs/software/social/#homer
Correct link: https://dietpi.com/docs/software/system_stats/#homer

**Version of DietPi-Dashboard**: 0.6.1

**Nightly or stable**: Nightly | Stable

**Version of DietPi**: 8.15.1 (beta)

**Comment by MichaIng** [comment]
Many thanks for reporting. Fixed here (as the dashboard is getting the info right from `dietpi-software`): https://github.com/MichaIng/DietPi/commit/5419d39
