### ISSUE TITLE
[Config] Dark mode config option + persistent store

### ISSUE THREAD

**Issue by MichaIng** [ravenclaw900/DietPi-Dashboard#52]
It would be great if the dark mode could be disabled via config file, respectively an initial default set by this, so that it can be still toggled via web UI. This goes hand in hand with the ability to have it stored in the browser so that reloading the page or opening at a later time does not reset it.

Adding and passing a setting in the backend is not an issue, but I'm stuck about how to pass this to the frontend. An own API/route only to get the setting is overkill, but there is no other direct way how the frontend can communicate with the backend, is it? In theory it could be passed via response header, but that would also mean that a request is done in JavaScript for that as it isn't possible to read/know headers which where send with the current page or script.

HTML, CSS and JavaScript is all statically created at compile time, right? The only other and probably best solution is to pass it via `socketData.darkMode` to be retrieved once in `socketOpenListener` and stored in localStorage from where it is read by the frontend?

**Comment by ravenclaw900** [comment]
Indeed, it could be passed with `update` and `login` in the "global" section. However, is this really worth a setting in the backend? It seems easier to just keep the dark mode setting in localStorage on the frontend, depending on what the user selected with the button.

**Comment by MichaIng** [comment]
> However, is this really worth a setting in the backend?

Maybe you're right. When we add color themes as well, I thought that allowing to set a default for new clients and when clearing browser data would be nice. But at least for now having it persistent in browser storage should be fine. We'll see whether a config file setting is required by others or not.
