### ISSUE TITLE
[Request] Upload and download files from File Browser

### ISSUE THREAD

**Issue by ravenclaw900** [ravenclaw900/DietPi-Dashboard#56]
From https://blog.login.gmbh/dietpi-7-8-ist-erschienen-das-sind-die-aenderungen/.
Definitely useful, and would remove the need for a file server in some cases.

**Comment by MichaIng** [comment]
I did read it but overlooked that request. Indeed that would be useful. Downloading files should be relatively trivial, not sure about uploading?

**Comment by Bwangster12** [comment]
Like having a file browser, but would love it to be more functional.  Downloading/uploading, a little more user friendly.  File Browser is a perfect example.

**Comment by ravenclaw900** [comment]
I'll see if I can make this happen with #123.
