### ISSUE TITLE
unable exit htop in terminal window, leaving terminal window with it running crashes dashboard completely

### ISSUE THREAD

**Issue by Black6spdZ** [ravenclaw900/DietPi-Dashboard#574]
unable exit htop in terminal window, leaving terminal window with it running crashes dashboard completely

DietPi-Dashboard [v0.6.1](https://github.com/ravenclaw900/DietPi-Dashboard/releases/tag/v0.6.1)

**Nightly or stable**: Stable

**Version of DietPi**: v8.18.2

**Device architecture**: armv8

**To Reproduce**
click on terminal
run htop
click to another tab such as software
dashboard becomes unresponsive

**Error log**
no error, dashboard just stops working

**Comment by ravenclaw900** [comment]
Closing this due to no response. If you still have an issue, please feel free to reopen.
