### ISSUE TITLE
Can't change the port

### ISSUE THREAD

**Issue by trifa13** [ravenclaw900/DietPi-Dashboard#59]
Hi,

I use the DietPi-Dashboard provided with DietPi v7.8.2 on NannoPI NEO 3. I also run another software on port 8088, so I tried to change it in /opt/dietpi-dashboard/config.toml - if I started from the same directory, e.g., /opt/dietpi-dashboard - it works with the new port, but if I start it from another directory or as a service it tries to use the default 8088 port and fails.

Regards

**Comment by MichaIng** [comment]
Probably it looks for the `config.toml` in the current directory rather than the directory where the executable is located. But then our service shouldn't work either as it doesn't set the working directory 🤔.

**Comment by MichaIng** [comment]
Works well with the default service shipped by `dietpi-software`:
```
~# systemctl cat dietpi-dashboard.service
# /etc/systemd/system/dietpi-dashboard.service
[Unit]
Description=Web Dashboard (DietPi)
Wants=network-online.target
After=network-online.target

[Service]
ExecStart=/opt/dietpi-dashboard/dietpi-dashboard

StandardInput=tty
TTYPath=/dev/tty42
StandardOutput=journal

[Install]
WantedBy=multi-user.target
```
Also running the binary from a different directory works 🤔:
```
2021-11-30 02:39:34 root@VM-Bullseye:~# /opt/dietpi-dashboard/dietpi-dashboard
INFO [warp::server] Server::run; addr=0.0.0.0:8089
INFO [warp::server] listening on http://0.0.0.0:8089
```
Tested with latest nightly build.

**Comment by ravenclaw900** [comment]
I actually just fixed this issue (https://github.com/ravenclaw900/DietPi-Dashboard/commit/5965551fec41d355749c92c9c743c75b536bd815). It should work with the latest stable or nightly.

**Comment by trifa13** [comment]
I've just tested it with the nightly build and it works as expected. Closing the issue...
Thanks
