### ISSUE TITLE
[Bug] Terminal sometimes freezes

### ISSUE THREAD

**Issue by ravenclaw900** [ravenclaw900/DietPi-Dashboard#70]
The terminal page seems to freeze if there's a large amount of input, either from a running command or from a lot of typing. However, input is still sent through the websocket. Need to test if this is a backend or frontend problem.

**Comment by ravenclaw900** [comment]
Alright, https://github.com/ravenclaw900/DietPi-Dashboard/commit/fd7711c2bf06617e81ac924c8aa7e31b1d42ae23 strips the up to 512 null characters from the output, and drops the buffer size to 256. This should fix most of the problems about output, hopefully.

**Comment by Joulinar** [comment]
not sure if it is related but at the moment I'm not able to open the terminal at all using latest nightly 0.4.1.

**Comment by ravenclaw900** [comment]
Fixed with https://github.com/ravenclaw900/DietPi-Dashboard/commit/7a476614d34cce3649545597430f550543bd9505, related to #105.

**Comment by ravenclaw900** [comment]
Hrm, tested out an old Go version of the dashboard, and the terminal doesn't freeze there, so it makes me wonder if it's a problem with `warp` or `pty_process`.

**Comment by ravenclaw900** [comment]
OK, so it's a problem with the thread reading from the PTY and sending through the websocket. Maybe a concurrency issue with the split websocket? I'll try wrapping it in a `Mutex`.

**Comment by ravenclaw900** [comment]
Well, that's the problem, some sort of concurrency issue, but we can't really synchronize access because it `awaits` for a message, and using a `Mutex` only lets things appear when typing as it passes access back and forth. Do you think that this is worth a bug report on the `warp` side?
