### ISSUE TITLE
Intel NUC 7 wrong temp

### ISSUE THREAD

**Issue by firefoot007** [ravenclaw900/DietPi-Dashboard#701]
**Describe the bug**:

Dietpi-Dashboard gives wrong -263F temperature for Intel NUC 7 platform.

**Version of DietPi-Dashboard**: 0.6.2

**Nightly or stable**: Stable

**Version of DietPi**: Latest

**Device architecture**: x86_64

**To Reproduce**
Just go directly to the homepage.

**Additional context**
Similar problem to this (https://github.com/MichaIng/DietPi/issues/3412)

**Comment by MichaIng** [comment]
Could you test this with the nightly version please? Just reinstall the dashboard for migrate:
```sh
dietpi-software reinstall 200
```

**Comment by firefoot007** [comment]
Thanks for your reply and awesome tool.

But sadly, it did not work with the nightly version too. I am attaching screenshots. I can provide logs if you want too. 


<img width="892" alt="Screenshot 2023-12-17 015325" src="https://github.com/ravenclaw900/DietPi-Dashboard/assets/37212464/bc6c990b-1d4b-4cb6-ab06-ab710547bdd1">
<img width="548" alt="Screenshot 2023-12-17 015203" src="https://github.com/ravenclaw900/DietPi-Dashboard/assets/37212464/50caaba6-0550-42f9-ac35-818946a6a0a8">

**Comment by MichaIng** [comment]
Okay, sadly this is a pretty known issue with those NUC boxes. They have a very strange non-standard thermal nodes. Does the DietPi console itself show the correct temperature, i.e. what does the `cpu` command show from console?

If it shows nonsense as well, can you check all thermal nodes?
```sh
for i in /sys/class/thermal/thermal_zone[0-9]/temp /sys/class/hwmon/hwmon[0-9]/temp[0-9]_input /sys/devices/platform/coretemp.[0-9]/hwmon/hwmon[0-9]/temp[0-9]_input
do [[ -e $i ]] && echo "$i: $(<$i)"
done
```

**Comment by firefoot007** [comment]
This is the same issue as that thread that I mentioned as the DietPi console shows the right temperature for me.

The output for all thermal nodes is as follows 

`/sys/class/thermal/thermal_zone0/temp: -263200
/sys/class/thermal/thermal_zone1/temp: 34500
/sys/class/thermal/thermal_zone2/temp: 36000
/sys/class/hwmon/hwmon0/temp1_input: -263200
/sys/class/hwmon/hwmon1/temp1_input: 34850
/sys/class/hwmon/hwmon1/temp2_input: 43850
/sys/class/hwmon/hwmon1/temp3_input: -150
/sys/class/hwmon/hwmon1/temp4_input: 34850
/sys/class/hwmon/hwmon2/temp1_input: 36000
/sys/class/hwmon/hwmon2/temp2_input: 35000
/sys/class/hwmon/hwmon2/temp3_input: 35000
/sys/class/hwmon/hwmon3/temp1_input: 34500
/sys/devices/platform/coretemp.0/hwmon/hwmon2/temp1_input: 36000
/sys/devices/platform/coretemp.0/hwmon/hwmon2/temp2_input: 35000
/sys/devices/platform/coretemp.0/hwmon/hwmon2/temp3_input: 35000
`

**Comment by MichaIng** [comment]
That is strange, the nightly build should prefer the coretemp nodes, which are correct. Did you restart the dashboard?
```sh
systemctl restart dietpi-dashboard
```

**Comment by firefoot007** [comment]
Yes, sorry for that. I did not restart the dashboard. Now it is showing correct values.

Thanks for your help.
