### ISSUE TITLE
service tabs is empty

### ISSUE THREAD

**Issue by GitzJoey** [ravenclaw900/DietPi-Dashboard#891]
hi
just recently (after dietpi upgrade 9.6.1
the service tab of dashboard suddenly become blank
![image](https://github.com/user-attachments/assets/afe168f4-d80d-40c8-981a-b0bfcd6b554d)

here's the console output
![image](https://github.com/user-attachments/assets/106fa645-a3da-4e6b-a9b9-97281f32fe21)

tested in Firefox and Edge, both yield the same

from journalctl
![image](https://github.com/user-attachments/assets/8ad5325c-6947-4440-9107-b792758b8940)

**Comment by MichaIng** [comment]
Is this the nightly or stable version of dietpi-dashboard? I checked the code but could not find where this error message is produced. Best match is: https://github.com/ravenclaw900/DietPi-Dashboard/blob/main/src/page_handlers.rs#L240

However, that would mean that it tried to run `systemctl get failed name`, while it should have done something like `systemctl start apache2` if you use start/stop services with this page.

Also not sure where the frontent calls `eval()`, but it is generated.

Also, a DietPi update does not update the dashboard (unless you did not have v0.6.2 yet, which as a security patch). Dud you try to restart it already?
```sh
systemctl restart dietpi-dashboard
```

**Comment by GitzJoey** [comment]
based on the footer
![image](https://github.com/user-attachments/assets/5462d309-18b6-4a1c-b654-8545b8e13f94)

and yes restart, even reboot already done but still empty

this might be the source, i'm not sure its usefull
![image](https://github.com/user-attachments/assets/79f9ff6c-59b6-4b20-b56b-0fccc4ff9af3)

**Comment by GitzJoey** [comment]
I found the issue,
is because dietpi-services status returning something like this
![image](https://github.com/user-attachments/assets/bab20291-a52b-47ef-a14e-920ca8e6462e)

once i fix the fail2ban, and running properly and the dietpi-services status
returning without any error, the websocket now returning array

would be good if can catch this or maybe returning some error messages
