### ISSUE TITLE
Temperature incorrect on NUC10i3

### ISSUE THREAD

**Issue by heimspielvier** [ravenclaw900/DietPi-Dashboard#996]
**Describe the bug**:
The dasboard shows an incorrect temperature on my dietpi installation on a NUC10i3

**Version of DietPi-Dashboard**:
v0.6.2

**Nightly or stable**: 
Stable

**Version of DietPi**:
9.8.0

**Device architecture**: 
x86_64

**To Reproduce**
On the main page of the dashboard the temperature is shown incorrectly in both the graph on the left hand side and the system stats on the right hand side(it shows -263 C).

**Error log**

**Additional context**
The cpu command in the terminal shows the correct temperature but the dashboard does not seem to pick up hat value

**Comment by MichaIng** [comment]
Sorry for the late reply. Can you change to the nighly build? Basically see here: #701

**Comment by heimspielvier** [comment]
Thanks for the reply. Just installed the nightly build and it seems to resolve the issue (the dashboard now shows 40 C).
Many thanks.

**Comment by MichaIng** [comment]
Great, I'll mark this as closed in favour of the existing issue.
